import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';
import { getIssuedBillingStatement } from './_billing-core.mjs';

const STORE='libra-accurate-sync';
const store=()=>getStore(STORE);
const now=()=>new Date().toISOString();
const clean=(v,n=300)=>String(v??'').trim().slice(0,n);
const money=v=>Math.trunc(Number(v)||0);

function authMode(){if(process.env.ACCURATE_API_TOKEN&&process.env.ACCURATE_API_SECRET)return 'API_TOKEN';if(process.env.ACCURATE_ACCESS_TOKEN&&process.env.ACCURATE_DB_ID)return 'OAUTH';return 'NOT_CONFIGURED';}
function accountMap(){return {customerDeposit:clean(process.env.ACCURATE_ACCOUNT_CUSTOMER_DEPOSIT,80),serviceRevenue:clean(process.env.ACCURATE_ACCOUNT_SERVICE_REVENUE,80),claimExpense:clean(process.env.ACCURATE_ACCOUNT_CLAIM_EXPENSE,80),adjustmentExpense:clean(process.env.ACCURATE_ACCOUNT_ADJUSTMENT_EXPENSE,80),bankClearing:clean(process.env.ACCURATE_ACCOUNT_BANK_CLEARING,80)};}
export function accurateConfigStatus(){const accounts=accountMap();return {authMode:authMode(),configured:authMode()!=='NOT_CONFIGURED',databaseId:process.env.ACCURATE_DB_ID?String(process.env.ACCURATE_DB_ID):null,accountMap:{...accounts},mappingReady:Boolean(accounts.customerDeposit&&accounts.serviceRevenue&&accounts.claimExpense&&accounts.adjustmentExpense),postingEnabled:false,postingNote:'Bridge saat ini memverifikasi koneksi, Chart of Accounts, dan menyiapkan queue jurnal. Push jurnal live tetap dikunci sampai schema/account mapping final disetujui Finance.'};}

function apiTokenHeaders(){const token=String(process.env.ACCURATE_API_TOKEN||'').trim(),secret=String(process.env.ACCURATE_API_SECRET||'').trim();if(!token||!secret)throw new Error('ACCURATE_API_TOKEN/API_SECRET belum dikonfigurasi.');const timestamp=String(Date.now());const signature=crypto.createHmac('sha256',secret).update(timestamp).digest('hex');return {'authorization':`Bearer ${token}`,'x-api-timestamp':timestamp,'x-api-signature':signature,'x-language-profile':'ID'};}
async function safeJson(response){const text=await response.text();try{return JSON.parse(text);}catch{return {s:false,d:[clean(text,500)]};}}
async function resolveApiTokenConnection(){const response=await fetch('https://account.accurate.id/api/api-token.do',{headers:apiTokenHeaders(),redirect:'follow'});const data=await safeJson(response);if(!response.ok||data?.s===false)throw new Error(`Accurate API Token gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,500)}`);const host=data?.d?.database?.host||data?.database?.host||data?.host||data?.d?.host;const database=data?.d?.database||data?.database||null;if(!host)throw new Error('Accurate tidak mengembalikan host database.');return {mode:'API_TOKEN',host:String(host).replace(/\/$/,''),session:null,database};}
async function resolveOauthConnection(){const token=String(process.env.ACCURATE_ACCESS_TOKEN||'').trim(),dbId=String(process.env.ACCURATE_DB_ID||'').trim();if(!token||!dbId)throw new Error('ACCURATE_ACCESS_TOKEN/DB_ID belum dikonfigurasi.');const url=new URL('https://account.accurate.id/api/open-db.do');url.searchParams.set('id',dbId);const response=await fetch(url,{headers:{authorization:`Bearer ${token}`},redirect:'follow'});const data=await safeJson(response);if(!response.ok||data?.s===false||!data?.host||!data?.session)throw new Error(`Accurate open-db gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,500)}`);return {mode:'OAUTH',host:String(data.host).replace(/\/$/,''),session:data.session,database:{id:dbId,alias:null}};}
export async function resolveAccurateConnection(){const mode=authMode();if(mode==='API_TOKEN')return resolveApiTokenConnection();if(mode==='OAUTH')return resolveOauthConnection();throw new Error('Koneksi Accurate belum dikonfigurasi.');}
function headersFor(connection){if(connection.mode==='API_TOKEN')return {...apiTokenHeaders(),'content-type':'application/json'};return {authorization:`Bearer ${String(process.env.ACCURATE_ACCESS_TOKEN||'').trim()}`,'x-session-id':connection.session,'content-type':'application/json'};}
export async function accurateGet(resource,action='list',params={}){const connection=await resolveAccurateConnection();const url=new URL(`${connection.host}/accurate/api/${clean(resource,80)}/${clean(action,40)}.do`);for(const [k,v] of Object.entries(params||{}))if(v!==null&&v!==undefined&&v!=='')url.searchParams.set(k,String(v));const response=await fetch(url,{method:'GET',headers:headersFor(connection),redirect:'follow'});const data=await safeJson(response);if(!response.ok||data?.s===false)throw new Error(`Accurate ${resource}/${action} gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,500)}`);return {connection,data};}
export async function testAccurateConnection(){const connection=await resolveAccurateConnection();let accountProbe=null;try{const result=await accurateGet('glaccount','list',{'sp.pageSize':1,'fields':'id,no,name'});accountProbe=Array.isArray(result.data?.d)?result.data.d[0]||null:null;}catch(error){accountProbe={error:clean(error?.message||error,300)};}return {ok:true,mode:connection.mode,host:connection.host,database:connection.database||null,accountProbe,testedAt:now()};}
export async function validateAccurateAccountMap(){const config=accurateConfigStatus();if(!config.configured)return {ok:false,message:'Koneksi Accurate belum dikonfigurasi.',accounts:[]};const {data}=await accurateGet('glaccount','list',{'sp.pageSize':200,'fields':'id,no,name,accountType'});const rows=Array.isArray(data?.d)?data.d:[];const byNo=new Map(rows.map(row=>[String(row.no||''),row]));const mapped=Object.entries(config.accountMap).filter(([,no])=>no).map(([role,no])=>({role,no,found:byNo.has(no),name:byNo.get(no)?.name||null,id:byNo.get(no)?.id||null}));return {ok:mapped.length>0&&mapped.every(x=>x.found),mapped,totalAccountsRead:rows.length};}

function journalEntries(report){const map=accountMap();const entries=[];const service=money(report.summary?.serviceCharge);if(service>0){entries.push({role:'CUSTOMER_DEPOSIT',accountNo:map.customerDeposit,debit:service,credit:0,memo:`Settlement deposit ${report.period.month}`});entries.push({role:'SERVICE_REVENUE',accountNo:map.serviceRevenue,debit:0,credit:service,memo:`Pendapatan jasa logistik ${report.period.month}`});}
 for(const line of report.lines||[]){if(line.type==='SERVICE')continue;const amount=money(line.amount);if(!amount)continue;if(amount>0){entries.push({role:'CUSTOMER_DEPOSIT',accountNo:map.customerDeposit,debit:amount,credit:0,memo:line.description});entries.push({role:'SERVICE_REVENUE',accountNo:map.serviceRevenue,debit:0,credit:amount,memo:line.description});}else{const value=Math.abs(amount);const expenseRole=line.type==='CLAIM_SETTLEMENT'?'CLAIM_EXPENSE':'ADJUSTMENT_EXPENSE';const expenseAccount=expenseRole==='CLAIM_EXPENSE'?map.claimExpense:map.adjustmentExpense;entries.push({role:expenseRole,accountNo:expenseAccount,debit:value,credit:0,memo:line.description});entries.push({role:'CUSTOMER_DEPOSIT',accountNo:map.customerDeposit,debit:0,credit:value,memo:line.description});}}
 return entries;
}
export function buildAccurateJournalDraft(report){const entries=journalEntries(report);const debit=entries.reduce((s,x)=>s+money(x.debit),0),credit=entries.reduce((s,x)=>s+money(x.credit),0);return {documentType:'JOURNAL_VOUCHER_DRAFT',source:'LIBRA_BILLING_STATEMENT',statementNo:report.statement?.statementNo||null,partnerId:report.partner.partnerId,period:report.period.month,transactionDate:report.period.endAt,description:`Libra billing ${report.partner.companyName} ${report.period.month}`,entries,totalDebit:debit,totalCredit:credit,balanced:debit===credit&&debit>0,mappingReady:entries.length>0&&entries.every(x=>Boolean(x.accountNo))};}
export async function queueStatementForAccurate(partnerId,month,actor='finance'){
 const report=await getIssuedBillingStatement(partnerId,month);if(!report)throw new Error('Statement harus di-issue terlebih dahulu sebelum masuk Accurate queue.');if(!report.snapshotHash)throw new Error('Statement belum memiliki snapshot hash yang valid.');
 const existing=(await listAccurateJobs(1000)).find(job=>job.statementHash===report.snapshotHash);if(existing)return {...existing,duplicate:true};
 const draft=buildAccurateJournalDraft(report);const jobId=`ACC-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;const createdAt=now();const row={jobId,status:draft.mappingReady&&draft.balanced?'READY_FOR_REVIEW':'NEEDS_MAPPING',partnerId:report.partner.partnerId,month:report.period.month,statementNo:report.statement.statementNo,statementHash:report.snapshotHash,journalDraft:draft,createdAt,createdBy:clean(actor,100),updatedAt:createdAt,lastError:null,postedAt:null,accurateReference:null,duplicate:false};await store().setJSON(`job/${createdAt}-${jobId}`,row,{onlyIfNew:true});return row;
}
export async function listAccurateJobs(limit=300){const {blobs}=await store().list({prefix:'job/'});const selected=blobs.sort((a,b)=>b.key.localeCompare(a.key)).slice(0,Math.max(1,Math.min(Number(limit)||300,1000)));const rows=[];for(const blob of selected){const row=await store().get(blob.key,{type:'json'});if(row)rows.push(row);}return rows;}
export async function getAccurateJob(jobId){return (await listAccurateJobs(1000)).find(x=>x.jobId===String(jobId||''))||null;}
export function accurateJobJson(job){return JSON.stringify({jobId:job.jobId,status:job.status,statementNo:job.statementNo,statementHash:job.statementHash,journalDraft:job.journalDraft},null,2);}
