import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';
import { getIssuedBillingStatement } from './_billing-core.mjs';

const STORE='libra-accurate-sync';
const store=()=>getStore(STORE);
const now=()=>new Date().toISOString();
const clean=(v,n=300)=>String(v??'').trim().slice(0,n);
const money=v=>Math.trunc(Number(v)||0);
const postingEnabled=()=>String(process.env.ACCURATE_POSTING_ENABLED||'').trim().toLowerCase()==='true';

function authMode(){if(process.env.ACCURATE_API_TOKEN&&process.env.ACCURATE_API_SECRET)return 'API_TOKEN';if(process.env.ACCURATE_ACCESS_TOKEN&&process.env.ACCURATE_DB_ID)return 'OAUTH';return 'NOT_CONFIGURED';}
function accountMap(){return {customerDeposit:clean(process.env.ACCURATE_ACCOUNT_CUSTOMER_DEPOSIT,80),serviceRevenue:clean(process.env.ACCURATE_ACCOUNT_SERVICE_REVENUE,80),claimExpense:clean(process.env.ACCURATE_ACCOUNT_CLAIM_EXPENSE,80),adjustmentExpense:clean(process.env.ACCURATE_ACCOUNT_ADJUSTMENT_EXPENSE,80),bankClearing:clean(process.env.ACCURATE_ACCOUNT_BANK_CLEARING,80)};}
export function accurateConfigStatus(){const accounts=accountMap(),enabled=postingEnabled();return {authMode:authMode(),configured:authMode()!=='NOT_CONFIGURED',databaseId:process.env.ACCURATE_DB_ID?String(process.env.ACCURATE_DB_ID):null,accountMap:{...accounts},mappingReady:Boolean(accounts.customerDeposit&&accounts.serviceRevenue&&accounts.claimExpense&&accounts.adjustmentExpense),postingEnabled:enabled,postingNote:enabled?'Production posting gate AKTIF. Setiap Journal Voucher tetap wajib lolos live connection + COA preflight dan maker-checker sebelum POST ke Accurate.':'Production posting gate TERKUNCI. Set ACCURATE_POSTING_ENABLED=true hanya setelah koneksi, scope Journal Voucher dan Chart of Accounts database PT Libra sudah diverifikasi.'};}

function apiTokenHeaders(){const token=String(process.env.ACCURATE_API_TOKEN||'').trim(),secret=String(process.env.ACCURATE_API_SECRET||'').trim();if(!token||!secret)throw new Error('ACCURATE_API_TOKEN/API_SECRET belum dikonfigurasi.');const timestamp=String(Date.now());const signature=crypto.createHmac('sha256',secret).update(timestamp).digest('hex');return {'authorization':`Bearer ${token}`,'x-api-timestamp':timestamp,'x-api-signature':signature};}
async function safeJson(response){const text=await response.text();try{return JSON.parse(text);}catch{return {s:false,d:[clean(text,500)]};}}
async function resolveApiTokenConnection(){const response=await fetch('https://account.accurate.id/api/api-token.do',{headers:apiTokenHeaders(),redirect:'follow'});const data=await safeJson(response);if(!response.ok||data?.s===false)throw new Error(`Accurate API Token gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,500)}`);const host=data?.d?.database?.host||data?.database?.host||data?.host||data?.d?.host;const database=data?.d?.database||data?.database||null;if(!host)throw new Error('Accurate tidak mengembalikan host database.');return {mode:'API_TOKEN',host:String(host).replace(/\/$/,''),session:null,database};}
async function resolveOauthConnection(){const token=String(process.env.ACCURATE_ACCESS_TOKEN||'').trim(),dbId=String(process.env.ACCURATE_DB_ID||'').trim();if(!token||!dbId)throw new Error('ACCURATE_ACCESS_TOKEN/DB_ID belum dikonfigurasi.');const url=new URL('https://account.accurate.id/api/open-db.do');url.searchParams.set('id',dbId);const response=await fetch(url,{headers:{authorization:`Bearer ${token}`},redirect:'follow'});const data=await safeJson(response);if(!response.ok||data?.s===false||!data?.host||!data?.session)throw new Error(`Accurate open-db gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,500)}`);return {mode:'OAUTH',host:String(data.host).replace(/\/$/,''),session:data.session,database:{id:dbId,alias:null}};}
export async function resolveAccurateConnection(){const mode=authMode();if(mode==='API_TOKEN')return resolveApiTokenConnection();if(mode==='OAUTH')return resolveOauthConnection();throw new Error('Koneksi Accurate belum dikonfigurasi.');}
function headersFor(connection,contentType=null){const headers=connection.mode==='API_TOKEN'?apiTokenHeaders():{authorization:`Bearer ${String(process.env.ACCURATE_ACCESS_TOKEN||'').trim()}`,'x-session-id':connection.session};if(contentType)headers['content-type']=contentType;return headers;}
export async function accurateGet(resource,action='list',params={}){const connection=await resolveAccurateConnection();const url=new URL(`${connection.host}/accurate/api/${clean(resource,80)}/${clean(action,40)}.do`);for(const [k,v] of Object.entries(params||{}))if(v!==null&&v!==undefined&&v!=='')url.searchParams.set(k,String(v));const response=await fetch(url,{method:'GET',headers:headersFor(connection),redirect:'follow'});const data=await safeJson(response);if(!response.ok||data?.s===false)throw new Error(`Accurate ${resource}/${action} gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,500)}`);return {connection,data};}
export async function testAccurateConnection(){const connection=await resolveAccurateConnection();let accountProbe=null;try{const result=await accurateGet('glaccount','list',{'sp.pageSize':1,'fields':'id,no,name'});accountProbe=Array.isArray(result.data?.d)?result.data.d[0]||null:null;}catch(error){accountProbe={error:clean(error?.message||error,300)};}return {ok:true,mode:connection.mode,host:connection.host,database:connection.database||null,accountProbe,testedAt:now()};}
export async function validateAccurateAccountMap(){
 const config=accurateConfigStatus();
 if(!config.configured)return {ok:false,message:'Koneksi Accurate belum dikonfigurasi.',mapped:[]};
 const rows=[];
 let page=1,pageCount=1;
 do{
  const {data}=await accurateGet('glaccount','list',{'sp.pageSize':100,'sp.page':page,'fields':'id,no,name,accountType'});
  const batch=Array.isArray(data?.d)?data.d:[];
  rows.push(...batch);
  const reported=Number(data?.sp?.pageCount)||1;
  pageCount=Math.max(1,Math.min(reported,100));
  page+=1;
 }while(page<=pageCount);
 const byNo=new Map(rows.map(row=>[String(row.no||'').trim(),row]));
 const mapped=Object.entries(config.accountMap).filter(([,no])=>no).map(([role,no])=>({role,no,found:byNo.has(String(no).trim()),name:byNo.get(String(no).trim())?.name||null,id:byNo.get(String(no).trim())?.id||null}));
 return {ok:mapped.length>=4&&mapped.every(x=>x.found),mapped,totalAccountsRead:rows.length,pagesRead:pageCount};
}

function journalEntries(report){const map=accountMap();const entries=[];const service=money(report.summary?.serviceCharge);if(service>0){entries.push({role:'CUSTOMER_DEPOSIT',accountNo:map.customerDeposit,debit:service,credit:0,memo:`Settlement deposit ${report.period.month}`});entries.push({role:'SERVICE_REVENUE',accountNo:map.serviceRevenue,debit:0,credit:service,memo:`Pendapatan jasa logistik ${report.period.month}`});}
 for(const line of report.lines||[]){if(line.type==='SERVICE')continue;const amount=money(line.amount);if(!amount)continue;if(amount>0){entries.push({role:'CUSTOMER_DEPOSIT',accountNo:map.customerDeposit,debit:amount,credit:0,memo:line.description});entries.push({role:'SERVICE_REVENUE',accountNo:map.serviceRevenue,debit:0,credit:amount,memo:line.description});}else{const value=Math.abs(amount);const expenseRole=line.type==='CLAIM_SETTLEMENT'?'CLAIM_EXPENSE':'ADJUSTMENT_EXPENSE';const expenseAccount=expenseRole==='CLAIM_EXPENSE'?map.claimExpense:map.adjustmentExpense;entries.push({role:expenseRole,accountNo:expenseAccount,debit:value,credit:0,memo:line.description});entries.push({role:'CUSTOMER_DEPOSIT',accountNo:map.customerDeposit,debit:0,credit:value,memo:line.description});}}
 return entries;
}
function periodLastInstant(endAt){const ms=new Date(endAt||0).getTime();return Number.isFinite(ms)?new Date(ms-1).toISOString():endAt;}
export function buildAccurateJournalDraft(report){const entries=journalEntries(report);const debit=entries.reduce((s,x)=>s+money(x.debit),0),credit=entries.reduce((s,x)=>s+money(x.credit),0);return {documentType:'JOURNAL_VOUCHER',source:'LIBRA_BILLING_STATEMENT',statementNo:report.statement?.statementNo||null,partnerId:report.partner.partnerId,period:report.period.month,transactionDate:periodLastInstant(report.period.endAt),description:`Libra billing ${report.partner.companyName} ${report.period.month}`,entries,totalDebit:debit,totalCredit:credit,balanced:debit===credit&&debit>0,mappingReady:entries.length>0&&entries.every(x=>Boolean(x.accountNo))};}
export async function queueStatementForAccurate(partnerId,month,actor='finance'){
 const report=await getIssuedBillingStatement(partnerId,month);if(!report)throw new Error('Statement harus di-issue terlebih dahulu sebelum masuk Accurate queue.');if(!report.snapshotHash)throw new Error('Statement belum memiliki snapshot hash yang valid.');
 const draft=buildAccurateJournalDraft(report);const jobId=`ACC-${report.snapshotHash.slice(0,20).toUpperCase()}`;const createdAt=now();const journalNumber=clean(report.statement?.statementNo||jobId,50);const row={jobId,status:draft.mappingReady&&draft.balanced?'READY_FOR_REVIEW':'NEEDS_MAPPING',partnerId:report.partner.partnerId,month:report.period.month,statementNo:report.statement.statementNo,statementHash:report.snapshotHash,journalNumber,journalDraft:draft,createdAt,createdBy:clean(actor,100),updatedAt:createdAt,lastError:null,postedAt:null,accurateReference:null,accurateId:null,approvalRequestId:null,duplicate:false};const key=`job/${report.snapshotHash}`;const result=await store().setJSON(key,row,{onlyIfNew:true});if(result.modified)return row;const existing=await store().get(key,{type:'json',consistency:'strong'});if(existing)return {...existing,duplicate:true};throw new Error('Accurate queue sedang diproses. Coba kembali.');
}
export async function listAccurateJobs(limit=300){const {blobs}=await store().list({prefix:'job/'});const selected=blobs.slice(0,Math.max(1,Math.min(Number(limit)||300,1000)));const rows=[];for(const blob of selected){const row=await store().get(blob.key,{type:'json'});if(row)rows.push(row);}return rows.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));}
export async function getAccurateJob(jobId){return (await listAccurateJobs(1000)).find(x=>x.jobId===String(jobId||''))||null;}
async function getAccurateJobEntry(jobId){const {blobs}=await store().list({prefix:'job/'});for(const blob of blobs){const entry=await store().getWithMetadata(blob.key,{type:'json',consistency:'strong'});if(entry?.data?.jobId===String(jobId||''))return {key:blob.key,...entry};}return null;}
function normalizeJob(row){return row?{...row,journalNumber:clean(row.journalNumber||row.statementNo||row.jobId,50)}:row;}
export function accurateJobJson(job){const row=normalizeJob(job);return JSON.stringify({jobId:row.jobId,status:row.status,statementNo:row.statementNo,statementHash:row.statementHash,journalNumber:row.journalNumber,journalDraft:row.journalDraft,approvalRequestId:row.approvalRequestId,accurateReference:row.accurateReference,accurateId:row.accurateId,postedAt:row.postedAt},null,2);}
function dateFromMonth(month,fallback){const match=/^(20\d{2})-(0[1-9]|1[0-2])$/.exec(String(month||''));if(match){const year=Number(match[1]),mon=Number(match[2]),day=new Date(Date.UTC(year,mon,0)).getUTCDate();return `${String(day).padStart(2,'0')}/${String(mon).padStart(2,'0')}/${year}`;}try{return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Asia/Jayapura'}).format(new Date(fallback));}catch{return '';}}
export function buildAccurateJournalPayload(jobInput){const job=normalizeJob(jobInput);if(!job?.journalDraft)throw new Error('Journal draft tidak tersedia.');const detailJournalVoucher=[];for(const line of job.journalDraft.entries||[]){const debit=money(line.debit),credit=money(line.credit);if(debit>0)detailJournalVoucher.push({accountNo:clean(line.accountNo,80),amount:debit,amountType:'DEBIT'});if(credit>0)detailJournalVoucher.push({accountNo:clean(line.accountNo,80),amount:credit,amountType:'CREDIT'});}return {number:job.journalNumber,transDate:dateFromMonth(job.month||job.journalDraft.period,job.journalDraft.transactionDate),description:clean(job.journalDraft.description,250),detailJournalVoucher};}
export async function preflightAccurateJob(jobId){const entry=await getAccurateJobEntry(jobId);if(!entry?.data)throw new Error('Accurate job tidak ditemukan.');const job=normalizeJob(entry.data),config=accurateConfigStatus();if(!config.configured)throw new Error('Koneksi Accurate belum dikonfigurasi.');if(!config.mappingReady)throw new Error('Chart of Accounts mapping belum lengkap.');if(job.status==='POSTED')return {ok:true,alreadyPosted:true,job,config,validation:null,payload:buildAccurateJournalPayload(job)};if(!['READY_FOR_REVIEW','APPROVAL_PENDING','RECONCILE_REQUIRED'].includes(job.status))throw new Error(`Job belum siap posting (${job.status}).`);if(!job.journalDraft?.balanced||!job.journalDraft?.mappingReady)throw new Error('Journal draft belum balanced/mapping ready.');const validation=await validateAccurateAccountMap();if(!validation.ok)throw new Error('Live Chart of Accounts validation gagal. Posting diblokir.');const payload=buildAccurateJournalPayload(job);if(!payload.number||!payload.transDate||payload.detailJournalVoucher.length<2)throw new Error('Payload Journal Voucher belum lengkap.');return {ok:true,alreadyPosted:false,job,config,validation,payload};}
export async function markAccurateApprovalRequested(jobId,approvalRequestId,actor='finance'){
 const entry=await getAccurateJobEntry(jobId);if(!entry?.data)throw new Error('Accurate job tidak ditemukan.');const current=normalizeJob(entry.data);if(current.status!=='READY_FOR_REVIEW')throw new Error(`Job tidak dapat diajukan approval dari status ${current.status}.`);const next={...current,status:'APPROVAL_PENDING',approvalRequestId:clean(approvalRequestId,120),approvalRequestedAt:now(),approvalRequestedBy:clean(actor,100),updatedAt:now()};const write=await store().setJSON(entry.key,next,{onlyIfMatch:entry.etag});if(!write.modified)throw new Error('Accurate job berubah di proses lain. Refresh lalu coba lagi.');return next;
}
export async function markAccurateApprovalRejected(jobId,approvalRequestId,actor='checker',note=''){
 const entry=await getAccurateJobEntry(jobId);if(!entry?.data)return null;const current=normalizeJob(entry.data);if(current.status!=='APPROVAL_PENDING'||current.approvalRequestId!==String(approvalRequestId||''))return current;const next={...current,status:'READY_FOR_REVIEW',approvalRequestId:null,approvalRejectedAt:now(),approvalRejectedBy:clean(actor,100),approvalRejectionNote:clean(note,500)||null,updatedAt:now()};const write=await store().setJSON(entry.key,next,{onlyIfMatch:entry.etag});if(!write.modified)throw new Error('Accurate job berubah saat reject approval.');return next;
}
async function accuratePostJournal(payload){const connection=await resolveAccurateConnection(),body=JSON.stringify(payload);let target=`${connection.host}/accurate/api/journal-voucher/save.do`;for(let attempt=0;attempt<2;attempt++){const response=await fetch(target,{method:'POST',headers:headersFor(connection,'application/json'),body,redirect:'manual'});const data=await safeJson(response);if(response.status===308&&attempt===0){const next=response.headers.get('location')||data?.endpoint;if(!next)throw new Error('Accurate mengembalikan redirect 308 tanpa endpoint baru.');target=new URL(next,target).toString();continue;}if(!response.ok||data?.s===false){const e=new Error(`Accurate journal-voucher/save gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,500)}`);e.accurateResponded=true;throw e;}return {data,host:new URL(target).origin};}throw new Error('Accurate redirect tidak dapat diselesaikan.');}
export async function postAccurateJob(jobId,actor='checker',approvalRequestId=''){
 if(!postingEnabled())throw new Error('ACCURATE_POSTING_ENABLED belum aktif.');const entry=await getAccurateJobEntry(jobId);if(!entry?.data)throw new Error('Accurate job tidak ditemukan.');const current=normalizeJob(entry.data);if(current.status==='POSTED')return current;if(current.status!=='APPROVAL_PENDING')throw new Error(`Job harus APPROVAL_PENDING sebelum posting, sekarang ${current.status}.`);if(current.approvalRequestId!==String(approvalRequestId||''))throw new Error('Approval request tidak cocok dengan Accurate job.');
 const preflight=await preflightAccurateJob(current.jobId);if(preflight.job.statementHash!==current.statementHash||preflight.payload.number!==current.journalNumber)throw new Error('Snapshot job berubah sejak approval dibuat. Buat approval baru.');const posting={...current,status:'POSTING',postingStartedAt:now(),postingBy:clean(actor,100),updatedAt:now()};const lock=await store().setJSON(entry.key,posting,{onlyIfMatch:entry.etag});if(!lock.modified)throw new Error('Accurate job sedang diproses admin lain.');
 try{const result=await accuratePostJournal(preflight.payload);const response=result.data||{},posted={...posting,status:'POSTED',postedAt:now(),updatedAt:now(),accurateReference:clean(response?.r?.number||preflight.payload.number,120),accurateId:response?.r?.id??null,accurateHost:result.host,lastError:null,responseDigest:crypto.createHash('sha256').update(JSON.stringify(response)).digest('hex')};await store().setJSON(entry.key,posted);return posted;}catch(error){const uncertain=!error?.accurateResponded;const failed={...posting,status:uncertain?'RECONCILE_REQUIRED':'POST_FAILED',lastError:clean(error?.message||error,500),failedAt:now(),updatedAt:now()};await store().setJSON(entry.key,failed);throw error;}
}
