import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';
import { buildPartnerReconciliation, monthBoundsWit, normalizeMonth } from './_reconciliation-core.mjs';
import { getPartner, getWallet, listPartners, mutateWallet, normalizePartnerId } from './_partner-core.mjs';

const STORE='libra-billing';
const store=()=>getStore(STORE);
const now=()=>new Date().toISOString();
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
const money=v=>Math.trunc(Number(v)||0);
const dueDays=()=>{const n=Math.trunc(Number(process.env.BILLING_DUE_DAYS||7));return Number.isFinite(n)?Math.max(0,Math.min(n,90)):7;};
const TAX_RATE=()=>{const n=Number(process.env.BILLING_TAX_RATE_PCT||0);return Number.isFinite(n)?Math.max(0,Math.min(n,100)):0;};
const ADJUSTMENT_KINDS=new Set(['DEBIT_NOTE','CREDIT_NOTE','REFUND','CLAIM_SETTLEMENT','OTHER']);

function inRange(value,bounds){const t=new Date(value||0).getTime();return Number.isFinite(t)&&t>=bounds.startMs&&t<bounds.endMs;}
function adjustmentKey(row){return `adjustment/${row.partnerId}/${row.createdAt}-${row.adjustmentId}`;}
function statementIndexKey(partnerId,month){return `statement-index/${partnerId}/${month}`;}
function agingBucket(outstanding,dueAt){if(outstanding<=0)return 'CURRENT';const days=Math.floor((Date.now()-new Date(dueAt||0).getTime())/86400000);if(!Number.isFinite(days)||days<=0)return 'CURRENT';if(days<=30)return '1-30';if(days<=60)return '31-60';if(days<=90)return '61-90';return '90+';}

export async function listFinanceAdjustments(partnerId,month=null,limit=1000){
 const id=normalizePartnerId(partnerId);if(!id)return [];const bounds=month?monthBoundsWit(month):null;const {blobs}=await store().list({prefix:`adjustment/${id}/`});const selected=blobs.sort((a,b)=>b.key.localeCompare(a.key)).slice(0,Math.max(1,Math.min(Number(limit)||1000,2000)));const rows=[];for(const blob of selected){const row=await store().get(blob.key,{type:'json'});if(row&&(!bounds||inRange(row.createdAt,bounds)))rows.push(row);}return rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
}

export async function applyFinanceAdjustment(input={},approval={}){
 const partnerId=normalizePartnerId(input.partnerId);if(!partnerId||!await getPartner(partnerId))throw new Error('Partner tidak ditemukan.');const signedAmount=money(input.signedAmount);if(!signedAmount||Math.abs(signedAmount)>10000000000)throw new Error('Nilai adjustment tidak valid.');const kind=ADJUSTMENT_KINDS.has(String(input.kind||'').toUpperCase())?String(input.kind).toUpperCase():(signedAmount>0?'DEBIT_NOTE':'CREDIT_NOTE');
 const adjustmentId=`ADJ-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;const walletDelta=-signedAmount;const reference=`BILLING:${approval.requestId||adjustmentId}`;const wallet=await mutateWallet(partnerId,walletDelta,reference,{source:'BILLING_ADJUSTMENT',description:clean(input.description||kind,300),metadata:{adjustmentId,kind,approvalRequestId:approval.requestId||null,bookingId:clean(input.bookingId,100)||null,claimReference:clean(input.claimReference,120)||null,maker:approval.maker||null,checker:approval.checker||null}});
 const createdAt=now();const row={adjustmentId,partnerId,kind,signedAmount,walletDelta,transactionId:wallet.transactionId,description:clean(input.description||kind,500),externalReference:clean(input.externalReference,160)||null,bookingId:clean(input.bookingId,100)||null,claimReference:clean(input.claimReference,120)||null,approvalRequestId:approval.requestId||null,maker:approval.maker||null,checker:approval.checker||null,createdAt};await store().setJSON(adjustmentKey(row),row,{onlyIfNew:true});return row;
}

export async function buildBillingStatement(partnerId,month){
 const id=normalizePartnerId(partnerId);if(!id)throw new Error('Partner ID tidak valid.');const period=normalizeMonth(month);const [reconciliation,adjustments,wallet]=await Promise.all([buildPartnerReconciliation(id,period),listFinanceAdjustments(id,period),getWallet(id)]);
 const billedBookings=reconciliation.rows.filter(row=>Boolean(row.transactionId));const pendingRows=reconciliation.rows.filter(row=>!row.transactionId&&!['PAYMENT_FAILED','WAITING_TOPUP','PAYMENT_PENDING'].includes(String(row.status||'').toUpperCase()));const serviceCharge=billedBookings.reduce((sum,row)=>sum+money(row.amount),0);const adjustmentNet=adjustments.reduce((sum,row)=>sum+money(row.signedAmount),0);const debitNotes=adjustments.filter(x=>x.signedAmount>0).reduce((s,x)=>s+money(x.signedAmount),0);const credits=adjustments.filter(x=>x.signedAmount<0).reduce((s,x)=>s+Math.abs(money(x.signedAmount)),0);const claimSettlements=adjustments.filter(x=>x.kind==='CLAIM_SETTLEMENT').reduce((s,x)=>s+Math.abs(money(x.signedAmount)),0);const netCharges=serviceCharge+adjustmentNet;const pendingAmount=pendingRows.reduce((sum,row)=>sum+money(row.amount),0);const taxRatePct=TAX_RATE();const taxAmount=taxRatePct>0?Math.round(Math.max(0,netCharges)*taxRatePct/100):0;
 // Tarif Libra saat ini dibayar dari deposit pada saat booking. Tax tidak otomatis mendebit wallet; aktifkan hanya setelah kebijakan billing/tax dikonfirmasi.
 const outstanding=Math.max(0,pendingAmount);const bounds=monthBoundsWit(period);const dueAt=new Date(bounds.endMs+dueDays()*86400000).toISOString();const lines=[...billedBookings.map(row=>({type:'SERVICE',reference:row.bookingId,bookingId:row.bookingId,partnerReference:row.partnerReference||null,description:`Pengiriman ${row.routeCode||''} ke ${row.destination?.kelurahan||'-'}`.trim(),amount:money(row.amount),createdAt:row.createdAt,trackingStatus:row.trackingStatus})),...adjustments.map(row=>({type:row.kind,reference:row.adjustmentId,bookingId:row.bookingId||null,claimReference:row.claimReference||null,description:row.description,amount:money(row.signedAmount),createdAt:row.createdAt,transactionId:row.transactionId}))].sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));
 return {partner:reconciliation.partner,period:reconciliation.period,statement:{status:'LIVE_PREVIEW',currency:'IDR',dueDays:dueDays(),dueAt,taxRatePct,taxAmount,taxMode:taxRatePct>0?'CONFIGURED_INFORMATIONAL':'NONE'},summary:{serviceCharge,adjustmentNet,debitNotes,credits,claimSettlements,netCharges,taxAmount,pendingAmount,outstanding,agingBucket:agingBucket(outstanding,dueAt),bookingCount:billedBookings.length,adjustmentCount:adjustments.length,deliveredCount:reconciliation.summary.deliveredCount,reconciliationIssueCount:reconciliation.summary.reconciliationIssueCount,depositCredits:reconciliation.summary.walletCreditPeriod,depositBookingDebits:reconciliation.summary.walletBookingDebitPeriod,currentWalletBalance:money(wallet.balance)},lines,reconciliation};
}

export async function issueBillingStatement(partnerId,month,actor='finance'){
 const report=await buildBillingStatement(partnerId,month);const id=report.partner.partnerId;const period=report.period.month;const indexKey=statementIndexKey(id,period);const current=await store().get(indexKey,{type:'json',consistency:'strong'});const version=Math.max(1,Number(current?.version||0)+1);const issuedAt=now();const statementNo=`LBR-STMT-${period.replace('-','')}-${id}-${String(version).padStart(2,'0')}`;const snapshot={...report,statement:{...report.statement,status:'ISSUED',statementNo,version,issuedAt,issuedBy:clean(actor,100)},snapshotHash:null};snapshot.snapshotHash=crypto.createHash('sha256').update(JSON.stringify({...snapshot,snapshotHash:null})).digest('hex');const key=`statement/${id}/${period}/${String(version).padStart(4,'0')}`;await store().setJSON(key,snapshot,{onlyIfNew:true});await store().setJSON(indexKey,{partnerId:id,month:period,version,key,statementNo,issuedAt,issuedBy:clean(actor,100),snapshotHash:snapshot.snapshotHash});return snapshot;
}
export async function getIssuedBillingStatement(partnerId,month){const id=normalizePartnerId(partnerId);const period=normalizeMonth(month);const idx=await store().get(statementIndexKey(id,period),{type:'json',consistency:'strong'});if(!idx)return null;return store().get(idx.key,{type:'json',consistency:'strong'});}
export async function listIssuedBillingStatements(limit=300){const {blobs}=await store().list({prefix:'statement-index/'});const selected=blobs.sort((a,b)=>b.key.localeCompare(a.key)).slice(0,Math.max(1,Math.min(Number(limit)||300,1000)));const rows=[];for(const blob of selected){const idx=await store().get(blob.key,{type:'json'});if(!idx)continue;const report=await store().get(idx.key,{type:'json'});if(report)rows.push(report);}return rows.sort((a,b)=>String(b.statement?.issuedAt||'').localeCompare(String(a.statement?.issuedAt||'')));}
export async function billingAgingSummary(){const statements=await listIssuedBillingStatements(1000);const latest=new Map();for(const row of statements){const key=`${row.partner.partnerId}:${row.period.month}`;if(!latest.has(key))latest.set(key,row);}const buckets={CURRENT:0,'1-30':0,'31-60':0,'61-90':0,'90+':0};let outstanding=0;for(const row of latest.values()){const value=money(row.summary?.outstanding);const bucket=agingBucket(value,row.statement?.dueAt);buckets[bucket]+=value;outstanding+=value;}return {outstanding,buckets,statementCount:latest.size};}
export async function listBillingPartners(){return listPartners();}

function csvCell(value){const text=String(value??'');return /[",\n\r]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}
export function billingStatementCsv(report){const h=['Statement No','Period','Partner ID','Line Type','Reference','Booking ID','Claim Ref','Description','Amount IDR','Created At'];const lines=[h.map(csvCell).join(',')];for(const row of report.lines||[])lines.push([report.statement?.statementNo||'LIVE',report.period.month,report.partner.partnerId,row.type,row.reference,row.bookingId,row.claimReference,row.description,row.amount,row.createdAt].map(csvCell).join(','));return '\uFEFF'+lines.join('\r\n');}
