import { cleanParty, findBookingByIdempotency, getBooking, newBookingId, reserveIdempotency, saveBooking, updateBooking, validateDestination } from './_booking-core.mjs';
import { finalizeQuote, getQuote, releaseQuote, reserveQuote } from './_quote-core.mjs';
import { getWallet, mutateWallet } from './_partner-core.mjs';

export async function createBookingForPartner(partner,input={},idempotencyKey,source='PORTAL'){
  const quoteId=String(input?.quoteId||'').trim().slice(0,100);const idem=String(idempotencyKey||input?.idempotencyKey||'').trim().slice(0,120);
  if(!quoteId||idem.length<8){const e=new Error('Quote ID dan Idempotency-Key minimal 8 karakter wajib diisi.');e.code='INVALID_BOOKING_REQUEST';throw e;}
  let existing=await findBookingByIdempotency(partner.partnerId,idem);if(existing?.status==='BOOKED')return {booking:existing,balance:(await getWallet(partner.partnerId)).balance,duplicate:true};
  const quote=await getQuote(quoteId);if(!quote){const e=new Error('Quote tidak ditemukan.');e.code='QUOTE_NOT_FOUND';throw e;}if(quote.partnerId!==partner.partnerId){const e=new Error('Quote bukan milik partner ini.');e.code='QUOTE_FORBIDDEN';throw e;}
  const destination=validateDestination(input?.destination||{},quote);const sender=cleanParty(input?.sender);const recipient=cleanParty(input?.recipient);if(!sender.name||!recipient.name||!recipient.phone||!recipient.address){const e=new Error('Nama pengirim, nama/HP/alamat penerima wajib diisi.');e.code='INVALID_PARTY';throw e;}
  let booking=existing;
  if(!booking){const proposedId=newBookingId();const reservation=await reserveIdempotency(partner.partnerId,idem,proposedId);if(!reservation.created){booking=await getBooking(reservation.bookingId);if(booking?.status==='BOOKED')return {booking,balance:(await getWallet(partner.partnerId)).balance,duplicate:true};}if(!booking){const createdAt=new Date().toISOString();booking={bookingId:proposedId,partnerId:partner.partnerId,quoteId,status:'PAYMENT_PENDING',source:String(source||'PORTAL').slice(0,20),idempotencyKey:idem,partnerReference:String(input?.partnerReference||'').trim().slice(0,120),sender,recipient,destination,weightKg:quote.weightKg,kodeRute:quote.kodeRute,amount:Number(quote.amount)||null,currency:'IDR',sla:quote.sla,masterVersion:quote.masterVersion,createdAt,updatedAt:createdAt};await saveBooking(booking,{onlyIfNew:true});}}
  let quoteReservation;
  try{quoteReservation=await reserveQuote(partner.partnerId,quoteId,booking.bookingId);const amount=Math.trunc(Number(quoteReservation.quote.amount));const wallet=await mutateWallet(partner.partnerId,-amount,`BOOKING:${booking.bookingId}`,{source:'BOOKING',description:`Booking ${booking.bookingId}`,metadata:{quoteId,kodeRute:quote.kodeRute,partnerReference:booking.partnerReference,source}});booking=await updateBooking(booking.bookingId,{status:'BOOKED',amount,transactionId:wallet.transactionId,bookedAt:new Date().toISOString(),paymentError:null});await finalizeQuote(quoteId,booking.bookingId,wallet.transactionId);return {booking,balance:wallet.balance,duplicate:wallet.duplicate};}
  catch(error){if(quoteReservation&&!quoteReservation.idempotent)await releaseQuote(quoteId,error?.code||error?.message||'BOOKING_FAILED');try{booking=await updateBooking(booking.bookingId,{status:error?.code==='INSUFFICIENT_BALANCE'?'WAITING_TOPUP':'PAYMENT_FAILED',paymentError:String(error?.message||'Booking gagal').slice(0,300)});}catch{}error.bookingId=booking?.bookingId;throw error;}
}
