import crypto from 'node:crypto';
import { accurateGet, resolveAccurateConnection, accurateConfigStatus } from './_accurate-core.mjs';

const clean=(v:unknown,n=700)=>String(v??'').trim().slice(0,n);
const money=(v:unknown)=>Math.max(0,Math.round(Number(v)||0));
const dbName=(db:any)=>clean(db?.alias||db?.name||db?.databaseName||db?.companyName,160);
const isTest=(s:string)=>/(test|tes|uat|sandbox)/i.test(s);
const sha=(v:unknown)=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
function apiHeaders(contentType=false){const token=clean(Netlify.env.get('ACCURATE_API_TOKEN'),3000),secret=clean(Netlify.env.get('ACCURATE_API_SECRET'),3000);if(!token||!secret)throw new Error('Credential Accurate API Token belum lengkap.');const timestamp=String(Date.now()),signature=crypto.createHmac('sha256',secret).update(timestamp).digest('hex');const h:any={authorization:`Bearer ${token}`,'x-api-timestamp':timestamp,'x-api-signature':signature};if(contentType)h['content-type']='application/json';return h;}
function headers(connection:any,contentType=false){if(connection.mode==='API_TOKEN')return apiHeaders(contentType);const token=clean(Netlify.env.get('ACCURATE_ACCESS_TOKEN'),4000);if(!token)throw new Error('Accurate OAuth token tidak tersedia.');const h:any={authorization:`Bearer ${token}`,'x-session-id':connection.session};if(contentType)h['content-type']='application/json';return h;}
async function json(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return {s:false,d:[clean(t,500)]}}}
async function call(connection:any,resource:string,action:string,method='GET',params:any={},body:any=null){const u=new URL(`${connection.host}/accurate/api/${resource}/${action}.do`);if(method==='GET')for(const [k,v] of Object.entries(params))if(v!==null&&v!==undefined&&v!=='')u.searchParams.set(k,String(v));let response:Response;try{response=await fetch(u,{method,headers:headers(connection,Boolean(body)),body:body?JSON.stringify(body):undefined,redirect:'follow'});}catch(e:any){e.networkUncertain=true;throw e;}const data=await json(response);if(!response.ok||data?.s===false){const e:any=new Error(`Accurate ${resource}/${action} gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,700)}`);e.accurateResponded=true;throw e;}return data;}
async function branchExists(){const {data}=await accurateGet('branch','list',{'sp.pageSize':100,'sp.page':1,fields:'id,name'});return (Array.isArray(data?.d)?data.d:[]).find((x:any)=>clean(x?.name,160).toLowerCase()==='hc kargo sentani')||null;}
function numberFor(sourceId:string,digest:string){return `LBR-HC-${clean(sourceId,30).replace(/[^A-Za-z0-9]/g,'').slice(-14).toUpperCase()}-${digest.slice(0,6).toUpperCase()}`.slice(0,50);}
async function findInvoice(connection:any,number:string){const data=await call(connection,'sales-invoice','list','GET',{'sp.pageSize':10,'sp.page':1,fields:'id,number,customerNo,totalAmount','filter.number.op':'EQUAL','filter.number.val[0]':number});const rows=Array.isArray(data?.d)?data.d:[];const exact=rows.filter((x:any)=>clean(x?.number||x?.no,80)===number);if(exact.length>1)throw new Error(`Duplicate critical: ${exact.length} faktur ${number}.`);return exact[0]||null;}
async function detail(connection:any,id:any){const data=await call(connection,'sales-invoice','detail','GET',{id});return data?.d||data?.r||data;}
function totalFromDetail(d:any){return money(d?.totalAmount??d?.total??d?.grandTotal);}
function verify(d:any,payload:any,total:number){return clean(d?.number||d?.no,80)===payload.number&&clean(d?.customerNo||d?.customer?.no,120)===payload.customerNo&&clean(d?.branchName||d?.branch?.name,160)==='HC Kargo Sentani'&&totalFromDetail(d)===total;}
export async function postHcSalesInvoice(preview:any,sourceId:string,meta:any={}){
 const cfg=accurateConfigStatus();if(!cfg.postingEnabled||!cfg.productionArmed)throw new Error('Accurate production posting belum dua-kunci aktif.');const expected=clean(Netlify.env.get('ACCURATE_PRODUCTION_DATABASE_NAME'),160);if(!expected)throw new Error('ACCURATE_PRODUCTION_DATABASE_NAME belum diset.');const connection=await resolveAccurateConnection(),actual=dbName(connection.database);if(!actual||isTest(actual)||actual.toLowerCase()!==expected.toLowerCase())throw new Error(`Database Accurate production tidak valid: ${actual||'tidak terbaca'}.`);const branch=await branchExists();if(!branch)throw new Error('Cabang HC Kargo Sentani tidak ditemukan di Accurate.');
 if(preview?.guard!=='PREVIEW_ONLY_NO_POST')throw new Error('Preview HC tidak valid.');const total=money(preview?.summary?.total),details=Array.isArray(preview?.detailItem)?preview.detailItem:[];if(!total||!details.length)throw new Error('Preview tagihan kosong.');const calculated=details.reduce((s:number,x:any)=>s+money(Number(x.quantity)*Number(x.unitPrice)),0);if(calculated!==total)throw new Error('Total detail berubah; POST diblokir.');
 const digest=sha({sourceId,customer:preview.customer,summary:preview.summary,detailItem:details}),number=numberFor(sourceId,digest);const payload:any={customerNo:preview.customer.no,branchName:'HC Kargo Sentani',currencyCode:'IDR',number,poNumber:clean(sourceId,120),transDate:clean(meta?.transDate,40)||undefined,description:clean(meta?.description,500)||`Libra Tools HC ${sourceId}`,detailItem:details.map((x:any)=>({itemNo:x.itemNo,quantity:x.quantity,unitPrice:x.unitPrice,detailName:x.detailName,detailNotes:x.detailNotes,departmentName:x.departmentName}))};
 const duplicate=await findInvoice(connection,number);if(duplicate){const d=await detail(connection,duplicate.id);if(!verify(d,payload,total))throw new Error(`Nomor ${number} sudah ada tetapi isi berbeda; reconcile manual wajib.`);return {status:'EXECUTED',idempotent:true,invoice:{id:duplicate.id,number,total,customerNo:payload.customerNo,branchName:'HC Kargo Sentani'},readBackVerified:true};}
 let posted=false,id:any=null;try{const result=await call(connection,'sales-invoice','save','POST',{},payload);posted=true;id=result?.r?.id??null;const returned=clean(result?.r?.number||result?.r?.no,80)||number;if(returned!==number){const e:any=new Error(`Accurate mengembalikan nomor ${returned}; expected ${number}.`);e.forceReconcile=true;throw e;}let d:any=null;if(id!==null)d=await detail(connection,id);else{const row=await findInvoice(connection,number);if(row)d=await detail(connection,row.id);}if(!d||!verify(d,payload,total)){const e:any=new Error('POST diterima tetapi read-back Faktur HC belum identik. Jangan retry otomatis.');e.forceReconcile=true;throw e;}return {status:'EXECUTED',idempotent:false,invoice:{id:d.id??id,number,total,customerNo:payload.customerNo,branchName:'HC Kargo Sentani'},readBackVerified:true};}catch(e:any){if(posted||e?.networkUncertain||e?.forceReconcile)throw new Error(`RECONCILE_REQUIRED: ${clean(e?.message||e,700)}`);throw e;}
}
