import crypto from 'node:crypto';
import { accurateGet, resolveAccurateConnection, accurateConfigStatus } from './_accurate-core.mjs';

const clean=(v:unknown,n=700)=>String(v??'').trim().slice(0,n);
const money=(v:unknown)=>Math.max(0,Math.round(Number(v)||0));
const dbName=(db:any)=>clean(db?.alias||db?.name||db?.databaseName||db?.companyName,160);
const isTest=(s:string)=>/(test|tes|uat|sandbox)/i.test(s);
const sha=(v:unknown)=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const HC_BRANCH='HC Kargo Sentani',HC_PROJECT='HC SPR',HC_DEPARTMENT='Kargo HC Sentani';
function accurateDate(v:unknown){const s=clean(v,80);if(!s)return undefined;let y=0,m=0,d=0;let x=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})(?:[T\s].*)?$/);if(x){y=Number(x[1]);m=Number(x[2]);d=Number(x[3]);}else{x=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);if(x){d=Number(x[1]);m=Number(x[2]);y=Number(x[3]);}else{x=s.match(/^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})$/);if(x){const months:any={jan:1,january:1,januari:1,feb:2,february:2,februari:2,mar:3,march:3,maret:3,apr:4,april:4,may:5,mei:5,jun:6,june:6,juni:6,jul:7,july:7,juli:7,aug:8,august:8,agu:8,agustus:8,sep:9,september:9,oct:10,october:10,okt:10,oktober:10,nov:11,november:11,dec:12,december:12,des:12,desember:12};d=Number(x[1]);m=months[x[2].toLowerCase()]||0;y=Number(x[3]);}}}if(!y||m<1||m>12||d<1||d>31)return undefined;return `${String(d).padStart(2,'0')}/${String(m).padStart(2,'0')}/${y}`;}
function apiHeaders(contentType?:string){const token=clean(Netlify.env.get('ACCURATE_API_TOKEN'),3000),secret=clean(Netlify.env.get('ACCURATE_API_SECRET'),3000);if(!token||!secret)throw new Error('Credential Accurate API Token belum lengkap.');const timestamp=String(Date.now()),signature=crypto.createHmac('sha256',secret).update(timestamp).digest('hex');const h:any={authorization:`Bearer ${token}`,'x-api-timestamp':timestamp,'x-api-signature':signature};if(contentType)h['content-type']=contentType;return h;}
function headers(connection:any,contentType?:string){if(connection.mode==='API_TOKEN')return apiHeaders(contentType);const token=clean(Netlify.env.get('ACCURATE_ACCESS_TOKEN'),4000);if(!token)throw new Error('Accurate OAuth token tidak tersedia.');const h:any={authorization:`Bearer ${token}`,'x-session-id':connection.session};if(contentType)h['content-type']=contentType;return h;}
async function json(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return {s:false,d:[clean(t,500)]}}}
function formBody(body:any){const p=new URLSearchParams();for(const [k,v] of Object.entries(body||{})){if(k==='detailItem'&&Array.isArray(v)){v.forEach((row:any,i:number)=>Object.entries(row||{}).forEach(([rk,rv])=>{if(rv!==null&&rv!==undefined&&rv!=='')p.append(`detailItem[${i}].${rk}`,String(rv))}));}else if(v!==null&&v!==undefined&&v!=='')p.append(k,String(v));}return p;}
async function call(connection:any,resource:string,action:string,method='GET',params:any={},body:any=null){const u=new URL(`${connection.host}/accurate/api/${resource}/${action}.do`);if(method==='GET')for(const [k,v] of Object.entries(params))if(v!==null&&v!==undefined&&v!=='')u.searchParams.set(k,String(v));const encoded=body?formBody(body):null;let response:Response;try{response=await fetch(u,{method,headers:headers(connection,encoded?'application/x-www-form-urlencoded;charset=UTF-8':undefined),body:encoded||undefined,redirect:'follow'});}catch(e:any){e.networkUncertain=true;throw e;}const data=await json(response);if(!response.ok||data?.s===false){const e:any=new Error(`Accurate ${resource}/${action} gagal: ${clean(data?.d?.join?.(' ')||data?.message||response.status,700)}`);e.accurateResponded=true;throw e;}return data;}
async function branchExists(){const {data}=await accurateGet('branch','list',{'sp.pageSize':100,'sp.page':1,fields:'id,name'});return (Array.isArray(data?.d)?data.d:[]).find((x:any)=>clean(x?.name,160).toLowerCase()===HC_BRANCH.toLowerCase())||null;}
function numberFor(sourceId:string,digest:string){return `LBR-HC-${clean(sourceId,30).replace(/[^A-Za-z0-9]/g,'').slice(-14).toUpperCase()}-${digest.slice(0,6).toUpperCase()}`.slice(0,50);}
async function findInvoice(connection:any,number:string){const data=await call(connection,'sales-invoice','list','GET',{'sp.pageSize':10,'sp.page':1,fields:'id,number,customerNo,totalAmount','filter.number.op':'EQUAL','filter.number.val[0]':number});const rows=Array.isArray(data?.d)?data.d:[];const exact=rows.filter((x:any)=>clean(x?.number||x?.no,80)===number);if(exact.length>1)throw new Error(`Duplicate critical: ${exact.length} faktur ${number}.`);return exact[0]||null;}
async function detail(connection:any,id:any){const data=await call(connection,'sales-invoice','detail','GET',{id});return data?.d||data?.r||data;}
function grandTotal(d:any){return money(d?.totalAmount??d?.total??d?.grandTotal??d?.netAmount);}
function subtotal(d:any){const direct=money(d?.subTotal??d?.subtotal??d?.subTotalAmount??d?.subtotalAmount);if(direct)return direct;const rows=Array.isArray(d?.detailItem)?d.detailItem:Array.isArray(d?.detailItems)?d.detailItems:[];return rows.reduce((s:number,x:any)=>s+money(x?.totalPrice??x?.totalAmount??(Number(x?.quantity||0)*Number(x?.unitPrice||0))),0);}
function customerNoFromDetail(d:any){return clean(d?.customerNo??d?.customer?.no??d?.customer?.customerNo??d?.customerCode??d?.customer?.code,120);}
function branchFromDetail(d:any){return clean(d?.branchName??d?.branch?.name??d?.branch?.branchName??d?.branch?.description,160);}
function numberFromDetail(d:any){return clean(d?.number??d?.no??d?.invoiceNo,80);}
function detailRows(d:any){return Array.isArray(d?.detailItem)?d.detailItem:Array.isArray(d?.detailItems)?d.detailItems:[];}
function rowDim(row:any,key:string){if(key==='department')return clean(row?.departmentName??row?.department?.name??row?.department?.departmentName,160);return clean(row?.projectName??row?.project?.name??row?.project?.projectName,160);}
function dimensionsOk(d:any){const rows=detailRows(d);if(!rows.length)return true;return rows.every((r:any)=>{const dep=rowDim(r,'department'),proj=rowDim(r,'project');return (!dep||dep.toLowerCase()===HC_DEPARTMENT.toLowerCase())&&(!proj||proj.toLowerCase()===HC_PROJECT.toLowerCase());});}
function verify(d:any,payload:any,total:number){const n=numberFromDetail(d),c=customerNoFromDetail(d),b=branchFromDetail(d),sub=subtotal(d);return (!n||n===payload.number)&&(!c||c===payload.customerNo)&&(!b||b.toLowerCase()===HC_BRANCH.toLowerCase())&&sub===total&&dimensionsOk(d);}
async function readBack(connection:any,number:string,id:any,total:number,payload:any){let d:any=null;if(id!==null&&id!==undefined){try{d=await detail(connection,id)}catch{d=null}}if(!d||!verify(d,payload,total)){const row=await findInvoice(connection,number);if(row){try{d=await detail(connection,row.id)}catch{d=row}}}return d;}
export async function postHcSalesInvoice(preview:any,sourceId:string,meta:any={}){
 const cfg=accurateConfigStatus();if(!cfg.postingEnabled||!cfg.productionArmed)throw new Error('Accurate production posting belum dua-kunci aktif.');const expected=clean(Netlify.env.get('ACCURATE_PRODUCTION_DATABASE_NAME'),160);if(!expected)throw new Error('ACCURATE_PRODUCTION_DATABASE_NAME belum diset.');const connection=await resolveAccurateConnection(),actual=dbName(connection.database);if(!actual||isTest(actual)||actual.toLowerCase()!==expected.toLowerCase())throw new Error(`Database Accurate production tidak valid: ${actual||'tidak terbaca'}.`);const branch=await branchExists();if(!branch)throw new Error(`Cabang ${HC_BRANCH} tidak ditemukan di Accurate.`);
 if(preview?.guard!=='PREVIEW_ONLY_NO_POST')throw new Error('Preview HC tidak valid.');const total=money(preview?.summary?.total),details=Array.isArray(preview?.detailItem)?preview.detailItem:[];if(!total||!details.length)throw new Error('Preview tagihan kosong.');const calculated=details.reduce((s:number,x:any)=>s+money(Number(x.quantity)*Number(x.unitPrice)),0);if(calculated!==total)throw new Error('Total detail berubah; POST diblokir.');
 const digest=sha({sourceId,customer:preview.customer,summary:preview.summary,detailItem:details}),number=numberFor(sourceId,digest),rawDate=clean(meta?.transDate,80),transDate=accurateDate(rawDate);if(rawDate&&!transDate)throw new Error(`Tanggal manifest tidak dapat dikonversi untuk Accurate: ${rawDate}.`);const payload:any={customerNo:preview.customer.no,branchName:HC_BRANCH,currencyCode:'IDR',number,poNumber:clean(sourceId,120),transDate,description:clean(meta?.description,500)||`Libra Tools HC ${sourceId}`,detailItem:details.map((x:any)=>({itemNo:x.itemNo,quantity:x.quantity,unitPrice:x.unitPrice,detailName:x.detailName,detailNotes:x.detailNotes,departmentName:HC_DEPARTMENT,projectName:HC_PROJECT}))};
 const duplicate=await findInvoice(connection,number);if(duplicate){const d=await readBack(connection,number,duplicate.id,total,payload);if(!d||!verify(d,payload,total))throw new Error(`Nomor ${number} sudah ada tetapi subtotal/dimensi berbeda; reconcile manual wajib.`);return {status:'EXECUTED',idempotent:true,invoice:{id:d?.id??duplicate.id,number,subtotal:total,total:grandTotal(d),customerNo:payload.customerNo,branchName:HC_BRANCH,projectName:HC_PROJECT,departmentName:HC_DEPARTMENT},readBackVerified:true};}
 let posted=false,id:any=null;try{const result=await call(connection,'sales-invoice','save','POST',{},payload);posted=true;id=result?.r?.id??null;const returned=clean(result?.r?.number||result?.r?.no,80)||number;if(returned!==number){const e:any=new Error(`Accurate mengembalikan nomor ${returned}; expected ${number}.`);e.forceReconcile=true;throw e;}const d=await readBack(connection,number,id,total,payload);if(!d||!verify(d,payload,total)){const rows=detailRows(d),dep=rows.map((r:any)=>rowDim(r,'department')).filter(Boolean).join('|')||'-',proj=rows.map((r:any)=>rowDim(r,'project')).filter(Boolean).join('|')||'-';const e:any=new Error(`POST diterima tetapi read-back belum cocok (number=${number}, customer=${customerNoFromDetail(d)||'-'}, branch=${branchFromDetail(d)||'-'}, subtotal=${subtotal(d)} expected=${total}, total+PPN=${grandTotal(d)}, project=${proj}, department=${dep}). Jangan retry otomatis.`);e.forceReconcile=true;throw e;}return {status:'EXECUTED',idempotent:false,invoice:{id:d.id??id,number,subtotal:total,total:grandTotal(d),customerNo:payload.customerNo,branchName:HC_BRANCH,projectName:HC_PROJECT,departmentName:HC_DEPARTMENT},readBackVerified:true};}catch(e:any){if(posted||e?.networkUncertain||e?.forceReconcile)throw new Error(`RECONCILE_REQUIRED: ${clean(e?.message||e,700)}`);throw e;}
}
