import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';
import { getBooking } from './_booking-core.mjs';

const STORE='libra-manifests';
const MODES=new Set(['AIR','TRUCK','SEA']);
const STATUSES=new Set(['OPEN','CLOSED','DEPARTED','ARRIVED','COMPLETED','CANCELLED']);
const PAYMENT_BLOCKED=new Set(['PAYMENT_PENDING','WAITING_TOPUP','PAYMENT_FAILED']);
function store(){return getStore(STORE);}
function clean(v,max=180){return String(v??'').trim().slice(0,max);}
function upper(v,max=180){return clean(v,max).toUpperCase();}
function now(){return new Date().toISOString();}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function sha256(v){return crypto.createHash('sha256').update(v).digest('hex');}
function stableHash(v){const copy={...v};delete copy.eventHash;return sha256(JSON.stringify(copy));}
function manifestKey(id){return `manifest/${clean(id,120)}`;}
function activeBookingKey(id){return `active-booking/${clean(id,120)}`;}
function newId(origin,destination){const date=new Date().toISOString().slice(0,10).replaceAll('-','');return `MNF-${upper(origin,10)||'ORG'}-${upper(destination,10)||'DST'}-${date}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;}

export async function getManifest(id){return store().get(manifestKey(id),{type:'json',consistency:'strong'});}
export async function getManifestWithMetadata(id){return store().getWithMetadata(manifestKey(id),{type:'json',consistency:'strong'});}
export async function listManifests(limit=200){const {blobs}=await store().list({prefix:'manifest/'});const rows=[];for(const blob of blobs.sort((a,b)=>b.key.localeCompare(a.key)).slice(0,Math.max(1,Math.min(limit,1000)))){const row=await store().get(blob.key,{type:'json'});if(row)rows.push(row);}return rows.sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)));}

async function appendEvent(manifest,input={}){const previous=await store().get(`head/${manifest.manifestId}`,{type:'json',consistency:'strong'});const createdAt=now();const event={eventId:`MNE-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`,manifestId:manifest.manifestId,type:upper(input.type,60),actor:clean(input.actor,100)||null,bookingId:clean(input.bookingId,120)||null,weightKg:finite(input.weightKg),note:clean(input.note,800)||null,metadata:input.metadata||null,previousEventHash:previous?.eventHash||null,createdAt};event.eventHash=stableHash(event);await store().setJSON(`event/${manifest.manifestId}/${createdAt}-${event.eventId}`,event,{onlyIfNew:true});await store().setJSON(`head/${manifest.manifestId}`,{eventId:event.eventId,eventHash:event.eventHash,createdAt});return event;}

function recalc(manifest){const items=Object.values(manifest.items||{});const declaredWeightKg=items.reduce((s,i)=>s+Number(i.declaredWeightKg||0),0);const actualWeightKg=items.reduce((s,i)=>s+Number(i.actualWeightKg||i.declaredWeightKg||0),0);const upliftWeightKg=items.reduce((s,i)=>s+Number(i.upliftWeightKg||0),0);const offloadWeightKg=items.reduce((s,i)=>s+Number(i.offloadWeightKg||0),0);const packageCount=items.reduce((s,i)=>s+Number(i.packageCount||0),0);return {...manifest,summary:{bookingCount:items.length,packageCount,declaredWeightKg:Math.round(declaredWeightKg*100)/100,actualWeightKg:Math.round(actualWeightKg*100)/100,upliftWeightKg:Math.round(upliftWeightKg*100)/100,offloadWeightKg:Math.round(offloadWeightKg*100)/100}};}
async function saveManifestCas(entry,next){const result=await store().setJSON(manifestKey(next.manifestId),recalc(next),entry?.etag?{onlyIfMatch:entry.etag}:{onlyIfNew:true});if(!result.modified)throw new Error('Manifest berubah di proses lain. Refresh lalu coba lagi.');return getManifest(next.manifestId);}

export async function createManifest(input={},actor='admin'){
  const origin=upper(input.origin,40),destination=upper(input.destination,40),mode=upper(input.mode,20);if(!origin||!destination)throw new Error('Origin dan destination wajib diisi.');if(!MODES.has(mode))throw new Error('Mode manifest harus AIR, TRUCK, atau SEA.');
  const createdAt=now();const manifestId=newId(origin,destination);const manifest=recalc({manifestId,status:'OPEN',mode,origin,destination,carrier:clean(input.carrier,140)||null,serviceNumber:clean(input.serviceNumber,80)||null,vehicleOrVessel:clean(input.vehicleOrVessel,120)||null,scheduledDepartureAt:clean(input.scheduledDepartureAt,40)||null,scheduledArrivalAt:clean(input.scheduledArrivalAt,40)||null,notes:clean(input.notes,1000)||null,items:{},createdAt,createdBy:clean(actor,100),updatedAt:createdAt});await store().setJSON(manifestKey(manifestId),manifest,{onlyIfNew:true});await appendEvent(manifest,{type:'MANIFEST_CREATED',actor,metadata:{mode,origin,destination,carrier:manifest.carrier,serviceNumber:manifest.serviceNumber}});return manifest;
}

export async function addBookingToManifest(manifestId,bookingId,input={},actor='admin'){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(manifest.status!=='OPEN')throw new Error('Booking hanya dapat ditambahkan saat manifest OPEN.');const booking=await getBooking(bookingId);if(!booking)throw new Error('Booking tidak ditemukan.');if(PAYMENT_BLOCKED.has(booking.status))throw new Error(`Booking ${booking.status} belum dapat dimanifestkan.`);if(booking.status==='DELIVERED')throw new Error('Booking sudah DELIVERED.');if(manifest.items?.[booking.bookingId])return manifest;
  const active=await store().get(activeBookingKey(booking.bookingId),{type:'text',consistency:'strong'});if(active&&active!==manifest.manifestId)throw new Error(`Booking masih aktif di manifest ${active}. Selesaikan/arrive manifest sebelumnya.`);
  const declared=Math.max(0,Number(booking.weightKg||0));const actual=finite(input.actualWeightKg);const packageCount=Math.max(1,Math.trunc(Number(input.packageCount||booking.packageCount||booking.koli||1)));const item={bookingId:booking.bookingId,partnerId:booking.partnerId||null,partnerReference:booking.partnerReference||null,declaredWeightKg:declared,actualWeightKg:Number.isFinite(actual)&&actual>0?actual:declared,packageCount,itemStatus:'MANIFESTED',upliftWeightKg:0,offloadWeightKg:0,addedAt:now(),addedBy:clean(actor,100),note:clean(input.note,500)||null};const next={...manifest,items:{...(manifest.items||{}),[booking.bookingId]:item},updatedAt:now()};const saved=await saveManifestCas(entry,next);await store().set(activeBookingKey(booking.bookingId),manifest.manifestId);await appendEvent(saved,{type:'BOOKING_ADDED',actor,bookingId:booking.bookingId,weightKg:item.actualWeightKg,metadata:{packageCount}});return saved;
}

export async function removeBookingFromManifest(manifestId,bookingId,actor='admin'){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(manifest.status!=='OPEN')throw new Error('Booking hanya dapat dilepas saat manifest OPEN.');if(!manifest.items?.[bookingId])return manifest;const items={...manifest.items};delete items[bookingId];const saved=await saveManifestCas(entry,{...manifest,items,updatedAt:now()});const active=await store().get(activeBookingKey(bookingId),{type:'text',consistency:'strong'});if(active===manifestId)await store().delete(activeBookingKey(bookingId));await appendEvent(saved,{type:'BOOKING_REMOVED',actor,bookingId});return saved;
}

export async function updateManifestItem(manifestId,bookingId,input={},actor='admin'){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(manifest.status!=='OPEN')throw new Error('Berat/koli hanya dapat diubah saat manifest OPEN.');const current=manifest.items?.[bookingId];if(!current)throw new Error('Booking tidak ada dalam manifest.');const actual=finite(input.actualWeightKg),packages=Math.trunc(Number(input.packageCount));if(!Number.isFinite(actual)||actual<=0)throw new Error('Actual weight wajib lebih dari 0.');if(!Number.isFinite(packages)||packages<1)throw new Error('Jumlah koli minimal 1.');const item={...current,actualWeightKg:Math.round(actual*100)/100,packageCount:packages,note:clean(input.note,500)||current.note,updatedAt:now(),updatedBy:clean(actor,100)};const saved=await saveManifestCas(entry,{...manifest,items:{...manifest.items,[bookingId]:item},updatedAt:now()});await appendEvent(saved,{type:'ITEM_REWEIGHED',actor,bookingId,weightKg:item.actualWeightKg,metadata:{packageCount:packages}});return saved;
}

export async function closeManifest(manifestId,actor='admin'){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(manifest.status==='CLOSED')return manifest;if(manifest.status!=='OPEN')throw new Error(`Manifest ${manifest.status} tidak dapat di-close.`);const summary=recalc(manifest).summary;if(!summary.bookingCount)throw new Error('Manifest kosong tidak dapat di-close.');if(summary.actualWeightKg<=0)throw new Error('Total actual weight harus lebih dari 0.');const closedAt=now();const itemsHash=sha256(JSON.stringify(manifest.items||{}));const saved=await saveManifestCas(entry,{...manifest,status:'CLOSED',closedAt,closedBy:clean(actor,100),itemsHash,updatedAt:closedAt});await appendEvent(saved,{type:'MANIFEST_CLOSED',actor,weightKg:saved.summary.actualWeightKg,metadata:{itemsHash,bookingCount:saved.summary.bookingCount,packageCount:saved.summary.packageCount}});return saved;
}

export async function recordUplift(manifestId,bookingId,weightKg,actor='admin',note=''){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(!['CLOSED','DEPARTED'].includes(manifest.status))throw new Error('Uplift hanya dapat dicatat setelah manifest CLOSED.');const current=manifest.items?.[bookingId];if(!current)throw new Error('Booking tidak ada dalam manifest.');const weight=finite(weightKg);if(!Number.isFinite(weight)||weight<=0)throw new Error('Berat uplift wajib lebih dari 0.');if(weight>Number(current.actualWeightKg||0))throw new Error('Berat uplift tidak boleh melebihi actual weight.');const item={...current,upliftWeightKg:Math.round(weight*100)/100,itemStatus:weight<Number(current.actualWeightKg||0)?'PARTIAL_UPLIFT':'UPLIFTED',upliftedAt:now(),upliftedBy:clean(actor,100)};const saved=await saveManifestCas(entry,{...manifest,items:{...manifest.items,[bookingId]:item},updatedAt:now()});await appendEvent(saved,{type:item.itemStatus,actor,bookingId,weightKg:item.upliftWeightKg,note});return saved;
}

export async function recordOffload(manifestId,bookingId,weightKg,actor='admin',note=''){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(!['CLOSED','DEPARTED'].includes(manifest.status))throw new Error('Offload hanya dapat dicatat pada manifest CLOSED/DEPARTED.');const current=manifest.items?.[bookingId];if(!current)throw new Error('Booking tidak ada dalam manifest.');const weight=finite(weightKg);if(!Number.isFinite(weight)||weight<=0)throw new Error('Berat offload wajib lebih dari 0.');if(weight>Number(current.upliftWeightKg||0))throw new Error('Offload tidak boleh melebihi berat uplift.');const item={...current,offloadWeightKg:Math.round(weight*100)/100,itemStatus:weight>=Number(current.upliftWeightKg||0)?'OFFLOADED':'PARTIAL_OFFLOAD',offloadedAt:now(),offloadedBy:clean(actor,100)};const saved=await saveManifestCas(entry,{...manifest,items:{...manifest.items,[bookingId]:item},updatedAt:now()});await appendEvent(saved,{type:item.itemStatus,actor,bookingId,weightKg:item.offloadWeightKg,note});return saved;
}

export async function departManifest(manifestId,actor='admin'){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(manifest.status==='DEPARTED')return manifest;if(manifest.status!=='CLOSED')throw new Error('Manifest harus CLOSED sebelum DEPARTED.');const summary=recalc(manifest).summary;if(summary.upliftWeightKg<=0)throw new Error('Belum ada uplift yang dicatat.');const at=now();const saved=await saveManifestCas(entry,{...manifest,status:'DEPARTED',departedAt:at,departedBy:clean(actor,100),updatedAt:at});await appendEvent(saved,{type:'MANIFEST_DEPARTED',actor,weightKg:saved.summary.upliftWeightKg});return saved;
}

export async function arriveManifest(manifestId,actor='admin'){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(manifest.status==='ARRIVED'||manifest.status==='COMPLETED')return manifest;if(manifest.status!=='DEPARTED')throw new Error('Manifest harus DEPARTED sebelum ARRIVED.');const at=now();const saved=await saveManifestCas(entry,{...manifest,status:'ARRIVED',arrivedAt:at,arrivedBy:clean(actor,100),updatedAt:at});for(const item of Object.values(saved.items||{})){const active=await store().get(activeBookingKey(item.bookingId),{type:'text',consistency:'strong'});if(active===saved.manifestId)await store().delete(activeBookingKey(item.bookingId));}await appendEvent(saved,{type:'MANIFEST_ARRIVED',actor,weightKg:saved.summary.upliftWeightKg});return saved;
}

export async function completeManifest(manifestId,actor='admin'){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(manifest.status==='COMPLETED')return manifest;if(manifest.status!=='ARRIVED')throw new Error('Manifest harus ARRIVED sebelum COMPLETED.');const at=now();const saved=await saveManifestCas(entry,{...manifest,status:'COMPLETED',completedAt:at,completedBy:clean(actor,100),updatedAt:at});await appendEvent(saved,{type:'MANIFEST_COMPLETED',actor});return saved;
}

export async function cancelManifest(manifestId,actor='admin',note=''){
  const entry=await getManifestWithMetadata(manifestId);const manifest=entry?.data;if(!manifest)throw new Error('Manifest tidak ditemukan.');if(!['OPEN','CLOSED'].includes(manifest.status))throw new Error('Manifest hanya dapat dibatalkan sebelum DEPARTED.');const at=now();const saved=await saveManifestCas(entry,{...manifest,status:'CANCELLED',cancelledAt:at,cancelledBy:clean(actor,100),updatedAt:at});for(const item of Object.values(saved.items||{})){const active=await store().get(activeBookingKey(item.bookingId),{type:'text',consistency:'strong'});if(active===saved.manifestId)await store().delete(activeBookingKey(item.bookingId));}await appendEvent(saved,{type:'MANIFEST_CANCELLED',actor,note});return saved;
}

export async function listManifestEvents(manifestId,limit=200){const {blobs}=await store().list({prefix:`event/${clean(manifestId,120)}/`});const rows=[];for(const blob of blobs.sort((a,b)=>a.key.localeCompare(b.key)).slice(-Math.max(1,Math.min(limit,500)))){const row=await store().get(blob.key,{type:'json'});if(row)rows.push(row);}return rows;}
export async function verifyManifestChain(manifestId){const rows=await listManifestEvents(manifestId,500);let previous=null;for(const row of rows){if((row.previousEventHash||null)!==previous)return {ok:false,eventId:row.eventId,reason:'PREVIOUS_HASH_MISMATCH'};if(stableHash(row)!==row.eventHash)return {ok:false,eventId:row.eventId,reason:'EVENT_HASH_MISMATCH'};previous=row.eventHash;}return {ok:true,count:rows.length,headHash:previous};}
export function manifestPolicy(){return {modes:[...MODES],statuses:[...STATUSES],activeBookingRule:'Satu booking hanya boleh berada pada satu manifest aktif per leg. Setelah ARRIVED booking dapat masuk manifest leg berikutnya.',closeRule:'Manifest OPEN dapat diedit; CLOSED membekukan daftar item dan menyimpan itemsHash.'};}
