import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';
import { getBooking } from './_booking-core.mjs';
import { getVerifiedOperationalWeight } from './_weight-core.mjs';

const STORE='libra-manifests';const MODES=new Set(['AIR','TRUCK','SEA']);const PAYMENT_BLOCKED=new Set(['PAYMENT_PENDING','WAITING_TOPUP','PAYMENT_FAILED']);
const store=()=>getStore(STORE);const clean=(v,m=180)=>String(v??'').trim().slice(0,m);const upper=(v,m=180)=>clean(v,m).toUpperCase();const now=()=>new Date().toISOString();const finite=v=>Number.isFinite(Number(v))?Number(v):null;const kg=v=>Math.round(Number(v||0)*100)/100;const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const stable=v=>{const c={...v};delete c.eventHash;return sha(JSON.stringify(c));};const mkey=id=>`manifest/${clean(id,120)}`;const akey=id=>`active-booking/${clean(id,120)}`;const newid=(o,d)=>`MNF-${upper(o,10)||'ORG'}-${upper(d,10)||'DST'}-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
export async function getManifest(id){return store().get(mkey(id),{type:'json',consistency:'strong'});}export async function getManifestWithMetadata(id){return store().getWithMetadata(mkey(id),{type:'json',consistency:'strong'});}export async function getActiveManifestId(bookingId){return store().get(akey(bookingId),{type:'text',consistency:'strong'});}export async function listManifests(limit=200){const {blobs}=await store().list({prefix:'manifest/'}),rows=[];for(const b of blobs.slice(0,Math.min(limit,1000))){const r=await store().get(b.key,{type:'json'});if(r)rows.push(r);}return rows.sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)));}
async function event(m,i={}){const p=await store().get(`head/${m.manifestId}`,{type:'json',consistency:'strong'}),createdAt=now();const e={eventId:`MNE-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`,manifestId:m.manifestId,type:upper(i.type,60),actor:clean(i.actor,100)||null,bookingId:clean(i.bookingId,120)||null,weightKg:finite(i.weightKg),note:clean(i.note,800)||null,metadata:i.metadata||null,previousEventHash:p?.eventHash||null,createdAt};e.eventHash=stable(e);await store().setJSON(`event/${m.manifestId}/${createdAt}-${e.eventId}`,e,{onlyIfNew:true});await store().setJSON(`head/${m.manifestId}`,{eventId:e.eventId,eventHash:e.eventHash,createdAt});return e;}
const mv=i=>{const actual=kg(i.actualWeightKg||i.declaredWeightKg),uplift=kg(i.upliftWeightKg),offload=kg(i.offloadWeightKg);return {actual,uplift,offload,net:kg(Math.max(0,uplift-offload)),remaining:kg(Math.max(0,actual-uplift))};};
function recalc(m){const it=Object.values(m.items||{}),sum=f=>kg(it.reduce((s,i)=>s+f(i),0));return {...m,summary:{bookingCount:it.length,packageCount:it.reduce((s,i)=>s+Number(i.packageCount||0),0),declaredWeightKg:sum(i=>Number(i.declaredWeightKg||0)),actualWeightKg:sum(i=>mv(i).actual),upliftWeightKg:sum(i=>mv(i).uplift),offloadWeightKg:sum(i=>mv(i).offload),netMovedWeightKg:sum(i=>mv(i).net),remainingWeightKg:sum(i=>mv(i).remaining),exceptionCount:it.filter(i=>mv(i).net<=0).length}};}
async function save(entry,next){const r=await store().setJSON(mkey(next.manifestId),recalc(next),entry?.etag?{onlyIfMatch:entry.etag}:{onlyIfNew:true});if(!r.modified)throw new Error('Manifest berubah di proses lain. Refresh lalu coba lagi.');return getManifest(next.manifestId);}
async function verifiedWeightSnapshot(bookingId){const w=await getVerifiedOperationalWeight(bookingId);if(!w)throw new Error('Berat aktual belum diverifikasi. Lakukan Actual Weight & Reweigh terlebih dahulu.');return w;}
export async function createManifest(i={},actor='admin'){const origin=upper(i.origin,40),destination=upper(i.destination,40),mode=upper(i.mode,20);if(!origin||!destination||origin===destination)throw new Error('Origin/destination tidak valid.');if(!MODES.has(mode))throw new Error('Mode manifest harus AIR, TRUCK, atau SEA.');const etd=clean(i.scheduledDepartureAt,40)||null,eta=clean(i.scheduledArrivalAt,40)||null;if(etd&&eta&&new Date(eta)<=new Date(etd))throw new Error('ETA harus setelah ETD.');const t=now(),manifest=recalc({manifestId:newid(origin,destination),status:'OPEN',mode,origin,destination,carrier:clean(i.carrier,140)||null,serviceNumber:clean(i.serviceNumber,80)||null,vehicleOrVessel:clean(i.vehicleOrVessel,120)||null,scheduledDepartureAt:etd,scheduledArrivalAt:eta,notes:clean(i.notes,1000)||null,items:{},createdAt:t,createdBy:clean(actor,100),updatedAt:t});await store().setJSON(mkey(manifest.manifestId),manifest,{onlyIfNew:true});await event(manifest,{type:'MANIFEST_CREATED',actor});return manifest;}
export async function addBookingToManifest(id,bid,i={},actor='admin'){const e=await getManifestWithMetadata(id),m=e?.data;if(!m||m.status!=='OPEN')throw new Error('Manifest tidak OPEN.');const b=await getBooking(bid);if(!b)throw new Error('Booking tidak ditemukan.');if(PAYMENT_BLOCKED.has(b.status)||b.status==='DELIVERED')throw new Error(`Booking ${b.status} tidak dapat dimanifestkan.`);if(m.items?.[b.bookingId])return m;const active=await getActiveManifestId(b.bookingId);if(active&&active!==m.manifestId)throw new Error(`Booking masih aktif di manifest ${active}.`);const w=await verifiedWeightSnapshot(b.bookingId);const actual=kg(w.actualWeightKg);if(actual<=0)throw new Error('Berat aktual terverifikasi tidak valid.');const item={bookingId:b.bookingId,partnerId:b.partnerId||null,partnerReference:b.partnerReference||null,declaredWeightKg:kg(b.weightKg||0),actualWeightKg:actual,chargeableWeightKg:kg(w.chargeableWeightKg),volumetricWeightKg:kg(w.volumetricWeightKg),packageCount:Math.max(1,Math.trunc(Number(w.packageCount||b.packageCount||b.koli||1))),weightVerifiedAt:w.verifiedAt,weightReweighCount:w.reweighCount,weightSource:'VERIFIED_WEIGHT',billingReviewRequired:Boolean(w.billingReviewRequired),itemStatus:'MANIFESTED',upliftWeightKg:0,offloadWeightKg:0,addedAt:now(),addedBy:clean(actor,100),note:clean(i.note,500)||null};const s=await save(e,{...m,items:{...m.items,[b.bookingId]:item},updatedAt:now()});await store().set(akey(b.bookingId),m.manifestId);await event(s,{type:'BOOKING_ADDED',actor,bookingId:b.bookingId,weightKg:actual,metadata:{weightSource:'VERIFIED_WEIGHT',weightVerifiedAt:w.verifiedAt}});return s;}
export async function removeBookingFromManifest(id,bid,actor='admin'){const e=await getManifestWithMetadata(id),m=e?.data;if(!m||m.status!=='OPEN')throw new Error('Booking hanya dapat dilepas saat OPEN.');if(!m.items?.[bid])return m;const items={...m.items};delete items[bid];const s=await save(e,{...m,items,updatedAt:now()});if(await getActiveManifestId(bid)===id)await store().delete(akey(bid));await event(s,{type:'BOOKING_REMOVED',actor,bookingId:bid});return s;}
export async function updateManifestItem(id,bid,i={},actor='admin'){const e=await getManifestWithMetadata(id),m=e?.data,c=m?.items?.[bid];if(!m||m.status!=='OPEN'||!c)throw new Error('Item manifest tidak dapat diubah.');const w=await verifiedWeightSnapshot(bid);const item={...c,actualWeightKg:kg(w.actualWeightKg),chargeableWeightKg:kg(w.chargeableWeightKg),volumetricWeightKg:kg(w.volumetricWeightKg),packageCount:Math.max(1,Math.trunc(Number(w.packageCount||c.packageCount||1))),weightVerifiedAt:w.verifiedAt,weightReweighCount:w.reweighCount,weightSource:'VERIFIED_WEIGHT',billingReviewRequired:Boolean(w.billingReviewRequired),note:clean(i.note,500)||c.note,updatedAt:now(),updatedBy:clean(actor,100)};const s=await save(e,{...m,items:{...m.items,[bid]:item},updatedAt:now()});await event(s,{type:'ITEM_WEIGHT_SYNCED',actor,bookingId:bid,weightKg:item.actualWeightKg,metadata:{weightVerifiedAt:w.verifiedAt,reweighCount:w.reweighCount}});return s;}
export async function closeManifest(id,actor='admin'){const e=await getManifestWithMetadata(id),m=e?.data;if(!m)throw new Error('Manifest tidak ditemukan.');if(m.status==='CLOSED')return m;if(m.status!=='OPEN')throw new Error('Manifest tidak dapat di-close.');for(const item of Object.values(m.items||{})){const w=await verifiedWeightSnapshot(item.bookingId);if(String(item.weightVerifiedAt||'')!==String(w.verifiedAt||'')||Number(item.weightReweighCount||0)!==Number(w.reweighCount||0))throw new Error(`Berat ${item.bookingId} berubah setelah masuk manifest. Sync ulang sebelum CLOSE.`);}const x=recalc(m);if(!x.summary.bookingCount||x.summary.actualWeightKg<=0)throw new Error('Manifest kosong/berat tidak valid.');const t=now(),itemsHash=sha(JSON.stringify(m.items||{})),s=await save(e,{...m,status:'CLOSED',closedAt:t,closedBy:clean(actor,100),itemsHash,updatedAt:t});await event(s,{type:'MANIFEST_CLOSED',actor,metadata:{itemsHash}});return s;}
export async function recordUplift(id,bid,w,actor='admin',note=''){const e=await getManifestWithMetadata(id),m=e?.data,c=m?.items?.[bid];if(!m||!['CLOSED','DEPARTED'].includes(m.status)||!c)throw new Error('Uplift tidak dapat dicatat.');const d=finite(w);if(!d||d<=0)throw new Error('Berat uplift tidak valid.');const x=mv(c),total=kg(x.uplift+d);if(total>x.actual)throw new Error('Total uplift melebihi actual weight.');const item={...c,upliftWeightKg:total,itemStatus:total<x.actual?'PARTIAL_UPLIFT':'UPLIFTED',upliftedAt:now(),upliftedBy:clean(actor,100)},s=await save(e,{...m,items:{...m.items,[bid]:item},updatedAt:now()});await event(s,{type:item.itemStatus,actor,bookingId:bid,weightKg:d,note,metadata:{cumulativeUpliftKg:total}});return s;}
export async function recordOffload(id,bid,w,actor='admin',note=''){const e=await getManifestWithMetadata(id),m=e?.data,c=m?.items?.[bid];if(!m||!['CLOSED','DEPARTED'].includes(m.status)||!c)throw new Error('Offload tidak dapat dicatat.');const d=finite(w);if(!d||d<=0)throw new Error('Berat offload tidak valid.');const x=mv(c),total=kg(x.offload+d);if(total>x.uplift)throw new Error('Total offload melebihi uplift.');const net=kg(x.uplift-total),item={...c,offloadWeightKg:total,itemStatus:net<=0?'OFFLOADED':'PARTIAL_OFFLOAD',offloadedAt:now(),offloadedBy:clean(actor,100)},s=await save(e,{...m,items:{...m.items,[bid]:item},updatedAt:now()});await event(s,{type:item.itemStatus,actor,bookingId:bid,weightKg:d,note,metadata:{cumulativeOffloadKg:total,netMovedKg:net}});return s;}
export async function departManifest(id,actor='admin'){const e=await getManifestWithMetadata(id),m=e?.data;if(!m)throw new Error('Manifest tidak ditemukan.');if(m.status==='DEPARTED')return m;if(m.status!=='CLOSED')throw new Error('Manifest harus CLOSED.');const x=recalc(m);if(x.summary.netMovedWeightKg<=0)throw new Error('Belum ada net uplift.');const t=now(),s=await save(e,{...m,status:'DEPARTED',departedAt:t,departedBy:clean(actor,100),updatedAt:t});await event(s,{type:'MANIFEST_DEPARTED',actor,weightKg:s.summary.netMovedWeightKg});return s;}
export async function arriveManifest(id,actor='admin'){const e=await getManifestWithMetadata(id),m=e?.data;if(!m)throw new Error('Manifest tidak ditemukan.');if(['ARRIVED','COMPLETED'].includes(m.status))return m;if(m.status!=='DEPARTED')throw new Error('Manifest harus DEPARTED.');const x=recalc(m);if(x.summary.netMovedWeightKg<=0)throw new Error('Tidak ada muatan yang tiba.');const t=now(),s=await save(e,{...m,status:'ARRIVED',arrivedAt:t,arrivedBy:clean(actor,100),updatedAt:t});for(const i of Object.values(s.items||{})){if(await getActiveManifestId(i.bookingId)===s.manifestId)await store().delete(akey(i.bookingId));}await event(s,{type:'MANIFEST_ARRIVED',actor,weightKg:s.summary.netMovedWeightKg,metadata:{exceptionCount:s.summary.exceptionCount}});return s;}
export async function completeManifest(id,actor='admin'){const e=await getManifestWithMetadata(id),m=e?.data;if(!m)throw new Error('Manifest tidak ditemukan.');if(m.status==='COMPLETED')return m;if(m.status!=='ARRIVED')throw new Error('Manifest harus ARRIVED.');const t=now(),s=await save(e,{...m,status:'COMPLETED',completedAt:t,completedBy:clean(actor,100),updatedAt:t});await event(s,{type:'MANIFEST_COMPLETED',actor,metadata:{exceptionCount:s.summary.exceptionCount}});return s;}
export async function cancelManifest(id,actor='admin',note=''){const e=await getManifestWithMetadata(id),m=e?.data;if(!m||!['OPEN','CLOSED'].includes(m.status))throw new Error('Manifest hanya dapat dibatalkan sebelum DEPARTED.');const t=now(),s=await save(e,{...m,status:'CANCELLED',cancelledAt:t,cancelledBy:clean(actor,100),updatedAt:t});for(const i of Object.values(s.items||{})){if(await getActiveManifestId(i.bookingId)===s.manifestId)await store().delete(akey(i.bookingId));}await event(s,{type:'MANIFEST_CANCELLED',actor,note});return s;}
export async function listManifestEvents(id,limit=200){const {blobs}=await store().list({prefix:`event/${clean(id,120)}/`}),rows=[];for(const b of blobs.sort((a,b)=>a.key.localeCompare(b.key)).slice(-Math.min(limit,500))){const r=await store().get(b.key,{type:'json'});if(r)rows.push(r);}return rows;}
export async function verifyManifestChain(id){const rows=await listManifestEvents(id,500);let p=null;for(const r of rows){if((r.previousEventHash||null)!==p)return {ok:false,eventId:r.eventId,reason:'PREVIOUS_HASH_MISMATCH'};if(stable(r)!==r.eventHash)return {ok:false,eventId:r.eventId,reason:'EVENT_HASH_MISMATCH'};p=r.eventHash;}return {ok:true,count:rows.length,headHash:p};}
