import { listBookings } from './_booking-core.mjs';
import { getPartner, getWallet, listWalletTransactions, normalizePartnerId } from './_partner-core.mjs';

const WIT_OFFSET_MS=9*60*60*1000;
const money=value=>Math.trunc(Number(value)||0);
function currentMonthWit(){const d=new Date(Date.now()+WIT_OFFSET_MS);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;}
export function normalizeMonth(value){const raw=String(value||currentMonthWit()).trim();const match=/^(20\d{2})-(0[1-9]|1[0-2])$/.exec(raw);if(!match)throw new Error('Periode harus format YYYY-MM.');return raw;}
export function monthBoundsWit(value){const month=normalizeMonth(value);const [year,mon]=month.split('-').map(Number);const startMs=Date.UTC(year,mon-1,1)-WIT_OFFSET_MS;const endMs=Date.UTC(year,mon,1)-WIT_OFFSET_MS;return {month,startIso:new Date(startMs).toISOString(),endIso:new Date(endMs).toISOString(),startMs,endMs};}
function inRange(value,bounds){const time=new Date(value||0).getTime();return Number.isFinite(time)&&time>=bounds.startMs&&time<bounds.endMs;}
function reconcileBooking(booking,ledgerMap){
  const amount=money(booking.amount);const transaction=booking.transactionId?ledgerMap.get(booking.transactionId)||null:null;let reconciliationStatus='UNPAID';let reconciliationNote='Booking belum memiliki debit saldo.';
  if(booking.transactionId&&!transaction){reconciliationStatus='MISSING_LEDGER';reconciliationNote='Booking memiliki transactionId tetapi ledger debit tidak ditemukan pada data yang dibaca.';}
  if(transaction){const expected=-Math.abs(amount);const actual=money(transaction.signedAmount);if(actual===expected){reconciliationStatus='MATCHED';reconciliationNote='Nominal booking cocok dengan debit wallet.';}else{reconciliationStatus='AMOUNT_MISMATCH';reconciliationNote=`Debit wallet ${actual} tidak sama dengan nilai booking ${expected}.`;}}
  return {bookingId:booking.bookingId,partnerReference:booking.partnerReference||null,source:booking.source||'PORTAL',createdAt:booking.createdAt,bookedAt:booking.bookedAt||null,status:booking.status,trackingStatus:booking.currentTrackingStatus||booking.status,routeCode:booking.kodeRute||null,weightKg:Number(booking.weightKg)||0,amount,currency:booking.currency||'IDR',transactionId:booking.transactionId||null,reconciliationStatus,reconciliationNote,destination:{kelurahan:booking.destination?.kelurahan||null,distrik:booking.destination?.distrik||null,kabupatenKota:booking.destination?.kabupatenKota||null,kodeWilayah:booking.destination?.kodeWilayah||null},recipient:{name:booking.recipient?.name||null,phone:booking.recipient?.phone||null},deliveredAt:booking.deliveredAt||null,receiverName:booking.receiverName||null,podId:booking.podId||null,podAvailable:Boolean(booking.podId),hasIncident:Boolean(booking.hasIncident),incidentStatus:booking.incidentStatus||null,incidentNote:booking.incidentNote||null,claimStatus:booking.claimStatus||null,claimReference:booking.claimReference||null,ledger:transaction?{transactionId:transaction.transactionId,direction:transaction.direction,amount:money(transaction.amount),signedAmount:money(transaction.signedAmount),reference:transaction.reference,createdAt:transaction.createdAt}:null};
}
export async function buildPartnerReconciliation(partnerId,month){
  const id=normalizePartnerId(partnerId);if(!id)throw new Error('Partner ID tidak valid.');const partner=await getPartner(id);if(!partner)throw new Error('Partner tidak ditemukan.');const bounds=monthBoundsWit(month);
  const [allBookings,allLedger,wallet]=await Promise.all([listBookings(2000),listWalletTransactions(id,1000),getWallet(id)]);
  const periodBookings=allBookings.filter(row=>row.partnerId===id&&!row.uat&&row.source!=='API_UAT'&&inRange(row.createdAt,bounds));const periodLedger=allLedger.filter(row=>inRange(row.createdAt,bounds));
  const ledgerMap=new Map(allLedger.map(row=>[row.transactionId,row]));const rows=periodBookings.map(row=>reconcileBooking(row,ledgerMap)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
  const paid=rows.filter(row=>row.transactionId);const matched=rows.filter(row=>row.reconciliationStatus==='MATCHED');const issues=rows.filter(row=>row.reconciliationStatus!=='MATCHED');const credits=periodLedger.filter(row=>row.direction==='CREDIT').reduce((sum,row)=>sum+money(row.amount),0);const debits=periodLedger.filter(row=>row.direction==='DEBIT').reduce((sum,row)=>sum+money(row.amount),0);const bookingDebits=periodLedger.filter(row=>row.direction==='DEBIT'&&row.source==='BOOKING').reduce((sum,row)=>sum+money(row.amount),0);
  return {partner:{partnerId:id,companyName:partner.companyName||id,picName:partner.picName||null},period:{month:bounds.month,timezone:'Asia/Jayapura',startAt:bounds.startIso,endAt:bounds.endIso},summary:{bookingCount:rows.length,paidBookingCount:paid.length,deliveredCount:rows.filter(row=>row.trackingStatus==='DELIVERED').length,incidentCount:rows.filter(row=>row.hasIncident).length,totalBookingCharge:paid.reduce((sum,row)=>sum+money(row.amount),0),pendingBookingAmount:rows.filter(row=>!row.transactionId).reduce((sum,row)=>sum+money(row.amount),0),matchedCount:matched.length,reconciliationIssueCount:issues.length,walletCreditPeriod:credits,walletDebitPeriod:debits,walletBookingDebitPeriod:bookingDebits,currentWalletBalance:money(wallet.balance)},rows};
}
function csvCell(value){const text=String(value??'');return /[",\n\r]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}
export function reconciliationCsv(report){
  const header=['Booking ID','Partner Reference','Source','Created At','Status','Tracking Status','Route','Kelurahan','Distrik','Kab/Kota','Weight Kg','Amount IDR','Transaction ID','Reconciliation','Delivered At','Receiver','POD','Incident','Claim Status','Claim Reference'];
  const lines=[header.map(csvCell).join(',')];for(const row of report.rows){lines.push([row.bookingId,row.partnerReference,row.source,row.createdAt,row.status,row.trackingStatus,row.routeCode,row.destination.kelurahan,row.destination.distrik,row.destination.kabupatenKota,row.weightKg,row.amount,row.transactionId,row.reconciliationStatus,row.deliveredAt,row.receiverName,row.podAvailable?'YES':'NO',row.incidentStatus,row.claimStatus,row.claimReference].map(csvCell).join(','));}
  return '\uFEFF'+lines.join('\r\n');
}
