import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';
import { getBooking } from './_booking-core.mjs';
import { createOperationalNotification } from './_notification-core.mjs';
import { normalizePartnerId } from './_partner-core.mjs';

const STORE='libra-tickets';
const store=()=>getStore(STORE);
const now=()=>new Date().toISOString();
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
const sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
export const TICKET_STATUSES=['OPEN','IN_PROGRESS','WAITING_PARTNER','WAITING_INTERNAL','RESOLVED','CLOSED'];
export const TICKET_PRIORITIES=['P1','P2','P3','P4'];
export const TICKET_CATEGORIES=['TRACKING','PICKUP','DELIVERY','BILLING','CLAIM','API','GENERAL'];
const SLA={P1:{response:1,resolution:4},P2:{response:4,resolution:12},P3:{response:8,resolution:24},P4:{response:24,resolution:72}};
const BOOKING_REQUIRED=new Set(['TRACKING','PICKUP','DELIVERY','CLAIM']);
const TRANSITIONS={OPEN:new Set(['IN_PROGRESS','WAITING_PARTNER','WAITING_INTERNAL','RESOLVED','CLOSED']),IN_PROGRESS:new Set(['WAITING_PARTNER','WAITING_INTERNAL','RESOLVED','CLOSED']),WAITING_PARTNER:new Set(['IN_PROGRESS','WAITING_INTERNAL','RESOLVED','CLOSED']),WAITING_INTERNAL:new Set(['IN_PROGRESS','WAITING_PARTNER','RESOLVED','CLOSED']),RESOLVED:new Set(['IN_PROGRESS','CLOSED']),CLOSED:new Set()};
function ticketKey(id){return `ticket/${clean(id,120)}`;}
function partnerIndexKey(partnerId,createdAt,id){return `partner/${normalizePartnerId(partnerId)}/${createdAt}-${id}`;}
function eventPrefix(id){return `event/${clean(id,120)}/`;}
function headKey(id){return `head/${clean(id,120)}`;}
function eventHash(row){const copy={...row};delete copy.eventHash;return sha(JSON.stringify(copy));}
function priorityFor(category,subject,body){const text=`${subject} ${body}`.toLowerCase();if(category==='CLAIM')return 'P2';if(category==='API'&&/(down|outage|production|gagal total|tidak bisa akses)/i.test(text))return 'P2';return 'P3';}
function dueAt(createdAt,hours,extraMs=0){return new Date(new Date(createdAt).getTime()+hours*3600000+Math.max(0,Number(extraMs)||0)).toISOString();}
async function appendEvent(ticketId,type,actor,visibility='INTERNAL',details={}){const previous=await store().get(headKey(ticketId),{type:'json',consistency:'strong'});const createdAt=now(),eventId=`TKTEVT-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;const row={eventId,ticketId,type:clean(type,80),actor:clean(actor,100),visibility:visibility==='PARTNER'?'PARTNER':'INTERNAL',details:JSON.parse(JSON.stringify(details||{})),previousEventHash:previous?.eventHash||null,createdAt};row.eventHash=eventHash(row);await store().setJSON(`${eventPrefix(ticketId)}${createdAt}-${eventId}`,row,{onlyIfNew:true});await store().setJSON(headKey(ticketId),{eventId,eventHash:row.eventHash,createdAt});return row;}
export async function getTicket(id){return store().get(ticketKey(id),{type:'json',consistency:'strong'});}
async function getTicketEntry(id){return store().getWithMetadata(ticketKey(id),{type:'json',consistency:'strong'});}
export function ticketSla(ticket,at=Date.now()){
 const priority=TICKET_PRIORITIES.includes(ticket?.priority)?ticket.priority:'P3',cfg=SLA[priority],created=new Date(ticket.createdAt).getTime();const currentWait=ticket.status==='WAITING_PARTNER'&&ticket.waitingPartnerStartedAt?Math.max(0,at-new Date(ticket.waitingPartnerStartedAt).getTime()):0;const paused=Math.max(0,Number(ticket.waitingPartnerMs)||0)+currentWait;const responseDue=created+cfg.response*3600000;const resolutionDue=created+cfg.resolution*3600000+paused;const responseDone=Boolean(ticket.firstResponseAt);const resolutionDone=['RESOLVED','CLOSED'].includes(ticket.status);const responseBreached=!responseDone&&at>responseDue,resolutionBreached=!resolutionDone&&ticket.status!=='WAITING_PARTNER'&&at>resolutionDue;let risk='GREEN';if(responseBreached||resolutionBreached)risk='RED';else if(!responseDone&&at>responseDue-cfg.response*3600000*0.25)risk='YELLOW';else if(!resolutionDone&&ticket.status!=='WAITING_PARTNER'&&at>resolutionDue-cfg.resolution*3600000*0.2)risk='YELLOW';return {priority,responseHours:cfg.response,resolutionHours:cfg.resolution,responseDueAt:new Date(responseDue).toISOString(),resolutionDueAt:new Date(resolutionDue).toISOString(),responseBreached,resolutionBreached,risk,pausedWaitingPartnerMs:paused};
}
export async function createPartnerTicket(input={},partner){const partnerId=normalizePartnerId(partner?.partnerId);if(!partnerId)throw new Error('Partner tidak valid.');const category=clean(input.category,30).toUpperCase();if(!TICKET_CATEGORIES.includes(category))throw new Error('Kategori tiket tidak valid.');const subject=clean(input.subject,180),body=clean(input.body,3000),bookingId=clean(input.bookingId,120);if(subject.length<5||body.length<10)throw new Error('Subjek minimal 5 karakter dan pesan minimal 10 karakter.');if(BOOKING_REQUIRED.has(category)&&!bookingId)throw new Error(`Booking ID wajib untuk kategori ${category}.`);let booking=null;if(bookingId){booking=await getBooking(bookingId);if(!booking)throw new Error('Booking tidak ditemukan.');if(booking.partnerId!==partnerId)throw new Error('Booking bukan milik partner ini.');}
 const ticketId=`TKT-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`,createdAt=now(),priority=priorityFor(category,subject,body);const ticket={ticketId,partnerId,companyName:clean(partner.companyName,180)||partnerId,bookingId:bookingId||null,partnerReference:booking?.partnerReference||null,claimReference:booking?.claimReference||null,category,subject,status:'OPEN',priority,assignee:null,firstResponseAt:null,resolvedAt:null,closedAt:null,waitingPartnerStartedAt:null,waitingPartnerMs:0,reopenCount:0,lastPublicMessageAt:createdAt,lastMessageAt:createdAt,messageCount:1,createdAt,createdBy:`partner:${partnerId}`,updatedAt:createdAt,updatedBy:`partner:${partnerId}`};const write=await store().setJSON(ticketKey(ticketId),ticket,{onlyIfNew:true});if(!write.modified)throw new Error('Ticket ID sudah digunakan.');await store().setJSON(partnerIndexKey(partnerId,createdAt,ticketId),{ticketId,createdAt},{onlyIfNew:true});await appendEvent(ticketId,'TICKET_OPENED',`partner:${partnerId}`,'PARTNER',{category,subject,body,bookingId:ticket.bookingId,priority});try{await createOperationalNotification({partnerId,type:'CS_TICKET_OPENED',severity:priority==='P2'?'WARNING':'INFO',title:`Ticket baru ${ticketId}`,message:`${ticket.companyName}: ${subject}`,reference:ticketId,notifyPartner:false,notifyAdmin:true,adminLink:`/admin-tickets?ticket=${encodeURIComponent(ticketId)}`,dedupeKey:`ticket-open:${ticketId}`,metadata:{ticketId,partnerId,category,priority,bookingId:ticket.bookingId}});}catch{}return ticket;}
export async function listTickets(limit=500){const {blobs}=await store().list({prefix:'ticket/'});const selected=blobs.slice(0,Math.max(1,Math.min(Number(limit)||500,2000))),rows=[];for(const b of selected){const row=await store().get(b.key,{type:'json'});if(row)rows.push({...row,sla:ticketSla(row)});}const rank={RED:0,YELLOW:1,GREEN:2};return rows.sort((a,b)=>(rank[a.sla.risk]??9)-(rank[b.sla.risk]??9)||String(b.updatedAt).localeCompare(String(a.updatedAt)));}
export async function listPartnerTickets(partnerId,limit=150){const id=normalizePartnerId(partnerId);if(!id)return [];const {blobs}=await store().list({prefix:`partner/${id}/`});const selected=blobs.sort((a,b)=>b.key.localeCompare(a.key)).slice(0,Math.max(1,Math.min(Number(limit)||150,500))),rows=[];for(const b of selected){const idx=await store().get(b.key,{type:'json'});if(!idx?.ticketId)continue;const row=await getTicket(idx.ticketId);if(row)rows.push({...row,sla:ticketSla(row)});}return rows;}
export async function listTicketEvents(ticketId,{partnerVisibleOnly=false,limit=300}={}){const {blobs}=await store().list({prefix:eventPrefix(ticketId)});const selected=blobs.sort((a,b)=>a.key.localeCompare(b.key)).slice(-Math.max(1,Math.min(Number(limit)||300,1000))),rows=[];for(const b of selected){const row=await store().get(b.key,{type:'json'});if(row&&(!partnerVisibleOnly||row.visibility==='PARTNER'))rows.push(row);}return rows;}
export async function addTicketMessage(ticketIdValue,{message,visibility='PARTNER'}={},actor={type:'ADMIN',id:'admin',partnerId:null}){const ticketId=clean(ticketIdValue,120),entry=await getTicketEntry(ticketId);if(!entry?.data)throw new Error('Tiket tidak ditemukan.');const current=entry.data;if(current.status==='CLOSED')throw new Error('Tiket CLOSED tidak dapat ditambah pesan.');const type=String(actor.type||'ADMIN').toUpperCase(),isPartner=type==='PARTNER';if(isPartner&&normalizePartnerId(actor.partnerId)!==current.partnerId)throw new Error('Tiket bukan milik partner ini.');const text=clean(message,3000);if(text.length<2)throw new Error('Pesan terlalu pendek.');const publicVisibility=isPartner?'PARTNER':(visibility==='INTERNAL'?'INTERNAL':'PARTNER');const stamp=now();let next={...current,lastMessageAt:stamp,messageCount:Number(current.messageCount||0)+1,updatedAt:stamp,updatedBy:clean(actor.id,100)};if(publicVisibility==='PARTNER')next.lastPublicMessageAt=stamp;if(!isPartner&&publicVisibility==='PARTNER'&&!current.firstResponseAt)next.firstResponseAt=stamp;if(isPartner&&current.status==='RESOLVED'){next.status='IN_PROGRESS';next.resolvedAt=null;next.reopenCount=Number(current.reopenCount||0)+1;}
 const write=await store().setJSON(ticketKey(ticketId),next,{onlyIfMatch:entry.etag});if(!write.modified)throw new Error('Tiket berubah di proses lain. Refresh lalu coba lagi.');await appendEvent(ticketId,isPartner?'PARTNER_MESSAGE':(publicVisibility==='PARTNER'?'ADMIN_REPLY':'INTERNAL_NOTE'),clean(actor.id,100),publicVisibility,{message:text});try{if(isPartner)await createOperationalNotification({partnerId:current.partnerId,type:'CS_TICKET_REPLY',severity:'INFO',title:`Balasan partner ${ticketId}`,message:`${current.companyName}: ${text.slice(0,180)}`,reference:ticketId,notifyPartner:false,notifyAdmin:true,adminLink:`/admin-tickets?ticket=${encodeURIComponent(ticketId)}`,dedupeKey:`ticket-partner-message:${ticketId}:${stamp}`});else if(publicVisibility==='PARTNER')await createOperationalNotification({partnerId:current.partnerId,type:'CS_TICKET_REPLY',severity:'INFO',title:`Balasan Libra untuk ${ticketId}`,message:text.slice(0,300),reference:ticketId,notifyPartner:true,notifyAdmin:false,partnerLink:`/partner/support?ticket=${encodeURIComponent(ticketId)}`,dedupeKey:`ticket-admin-message:${ticketId}:${stamp}`});}catch{}return next;}
export async function updateTicketAdmin(ticketIdValue,patch={},actor='admin'){const ticketId=clean(ticketIdValue,120),entry=await getTicketEntry(ticketId);if(!entry?.data)throw new Error('Tiket tidak ditemukan.');const current=entry.data;if(current.status==='CLOSED')throw new Error('Tiket CLOSED dikunci.');let next={...current},changed={};if(patch.priority){const p=clean(patch.priority,10).toUpperCase();if(!TICKET_PRIORITIES.includes(p))throw new Error('Prioritas tidak valid.');next.priority=p;changed.priority=p;}if(patch.assignee!==undefined){next.assignee=clean(patch.assignee,100)||null;changed.assignee=next.assignee;}if(patch.status){const status=clean(patch.status,30).toUpperCase();if(!TICKET_STATUSES.includes(status)||status!==current.status&&!TRANSITIONS[current.status]?.has(status))throw new Error(`Transisi ${current.status} → ${status} tidak diizinkan.`);if(status!==current.status){const stamp=now();if(current.status==='WAITING_PARTNER'&&current.waitingPartnerStartedAt)next.waitingPartnerMs=Math.max(0,Number(current.waitingPartnerMs)||0)+Math.max(0,new Date(stamp).getTime()-new Date(current.waitingPartnerStartedAt).getTime());next.waitingPartnerStartedAt=status==='WAITING_PARTNER'?stamp:null;next.status=status;if(status==='RESOLVED')next.resolvedAt=stamp;if(status==='CLOSED')next.closedAt=stamp;if(current.status==='RESOLVED'&&status==='IN_PROGRESS'){next.resolvedAt=null;next.reopenCount=Number(current.reopenCount||0)+1;}changed.status=status;}}
 next.updatedAt=now();next.updatedBy=clean(actor,100);const write=await store().setJSON(ticketKey(ticketId),next,{onlyIfMatch:entry.etag});if(!write.modified)throw new Error('Tiket berubah di proses lain. Refresh lalu coba lagi.');await appendEvent(ticketId,'TICKET_UPDATED',actor,'PARTNER',{changes:changed,status:next.status,priority:next.priority,assignee:next.assignee});if(changed.status||changed.priority){try{await createOperationalNotification({partnerId:next.partnerId,type:'CS_TICKET_STATUS',severity:next.status==='RESOLVED'?'SUCCESS':'INFO',title:`Update tiket ${ticketId}`,message:`Status ${next.status}, prioritas ${next.priority}${next.assignee?`, PIC ${next.assignee}`:''}.`,reference:ticketId,notifyPartner:true,notifyAdmin:false,partnerLink:`/partner/support?ticket=${encodeURIComponent(ticketId)}`,dedupeKey:`ticket-status:${ticketId}:${next.updatedAt}`});}catch{}}return next;}
export async function verifyTicketChain(ticketId){const rows=await listTicketEvents(ticketId,{limit:1000});let previous=null;for(const row of rows){if((row.previousEventHash||null)!==previous)return {ok:false,eventId:row.eventId,reason:'PREVIOUS_HASH_MISMATCH'};if(eventHash(row)!==row.eventHash)return {ok:false,eventId:row.eventId,reason:'EVENT_HASH_MISMATCH'};previous=row.eventHash;}return {ok:true,count:rows.length,headHash:previous};}
export async function ticketSummary(){const rows=await listTickets(2000);return {total:rows.length,open:rows.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length,red:rows.filter(x=>x.sla.risk==='RED').length,yellow:rows.filter(x=>x.sla.risk==='YELLOW').length,waitingPartner:rows.filter(x=>x.status==='WAITING_PARTNER').length,waitingInternal:rows.filter(x=>x.status==='WAITING_INTERNAL').length,resolved:rows.filter(x=>x.status==='RESOLVED').length,closed:rows.filter(x=>x.status==='CLOSED').length,responseBreached:rows.filter(x=>x.sla.responseBreached).length,resolutionBreached:rows.filter(x=>x.sla.resolutionBreached).length};}
