import { writeAdminAudit } from './_admin-audit-core.mjs';
import { approveQuote, getQuote, listQuotes } from './_quote-core.mjs';
import { getAdminSession } from './_partner-core.mjs';

function esc(value){return String(value??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function money(value){return value===null||value===undefined?'—':'Rp'+Number(value).toLocaleString('id-ID');}
function sameOrigin(request){const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).origin===new URL(request.url).origin;}catch{return false;}}
function render(quotes,message='',error=''){
 const rows=quotes.map(q=>`<tr><td><b>${esc(q.quoteId)}</b><small>${esc(q.partnerId)}</small></td><td>${esc(q.kelurahan)}<small>${esc(q.distrik)} • ${esc(q.kodeRute)}</small></td><td>${Number(q.weightKg).toLocaleString('id-ID')} kg<small>Chargeable ${q.chargeableKg?Number(q.chargeableKg).toLocaleString('id-ID')+' kg':'—'}</small></td><td>${esc(q.status)}<small>${esc(q.approvalSource||'')}</small></td><td>${money(q.amount)}<small>${esc(q.ratePlanName||'Tanpa rate plan')}</small></td><td>${esc(q.sla||'—')}<small>Cut-off ${esc(q.cutoffWit||'—')} WIT</small></td><td>${q.status==='PENDING_APPROVAL'?`<form method="post" class="approve"><input type="hidden" name="quoteId" value="${esc(q.quoteId)}"><input name="amount" inputmode="numeric" placeholder="Nominal Rp" required><input name="note" placeholder="Alasan/manual pricing" required><button>Approve</button></form>`:esc(q.bookingId||'—')}</td></tr>`).join('');
 return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Quote & Booking</title><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:#f2f6fa;color:#10243d}.top{background:#061d36;color:#fff;padding:18px}.topin,.wrap{max-width:1320px;margin:auto}.topin{display:flex;justify-content:space-between}.top a{color:#fff}.wrap{padding:24px 18px}.notice{padding:12px;border-radius:10px;margin:12px 0;background:#e8f4ff}.err{background:#fff0ef}.card{background:#fff;border:1px solid #dce6ef;border-radius:15px;overflow:hidden}.tablewrap{overflow:auto}table{width:100%;min-width:1100px;border-collapse:collapse;font-size:12px}th,td{padding:10px;border-bottom:1px solid #edf1f5;text-align:left;vertical-align:top}th{background:#f7fafc}small{display:block;color:#718397;margin-top:4px}.approve{display:grid;grid-template-columns:120px 180px auto;gap:6px}.approve input,.approve button{padding:8px;border-radius:8px;border:1px solid #cbd8e6}.approve button{background:#167348;color:#fff;border:0;font-weight:800}</style></head><body><header class="top"><div class="topin"><strong>LIBRA • Quote & Booking</strong><a href="/libra-admin">← Home Admin</a></div></header><main class="wrap"><h1>Quote & Booking Control</h1><p>Approval harga manual wajib alasan dan tercatat di Audit Trail.</p>${message?`<div class="notice">${esc(message)}</div>`:''}${error?`<div class="notice err">${esc(error)}</div>`:''}<section class="card"><div class="tablewrap"><table><thead><tr><th>Quote / Partner</th><th>Tujuan</th><th>Berat</th><th>Status</th><th>Harga</th><th>SLA</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="7">Belum ada quote.</td></tr>'}</tbody></table></div></section><p><a href="/admin-audit-backup">Audit Trail & Backup →</a></p></main></body></html>`;
}

export default async request=>{
 const session=getAdminSession(request);if(!session)return Response.redirect(new URL('/libra-admin-login.html',request.url),302);let message='',error='';
 if(request.method==='POST'){
  if(!sameOrigin(request))return new Response('Forbidden',{status:403});const form=await request.formData();const quoteId=String(form.get('quoteId')||'');
  try{const before=await getQuote(quoteId);const quote=await approveQuote(quoteId,form.get('amount'),form.get('note'));message=`${quote.quoteId} disetujui ${money(quote.amount)} dan berlaku 30 menit.`;await writeAdminAudit({session,request,action:'QUOTE_MANUAL_APPROVE',entityType:'QUOTE',entityId:quote.quoteId,before,after:quote,note:String(form.get('note')||''),metadata:{approvedAmount:Number(quote.amount)}});}
  catch(err){error=err?.message||'Quote gagal disetujui.';}
 }else if(request.method!=='GET')return new Response('Method not allowed',{status:405});
 const quotes=await listQuotes(200);return new Response(render(quotes,message,error),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-frame-options':'DENY','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"}});
};
export const config={path:'/admin-quotes'};
