import { validAdminSession } from './_partner-core.mjs';
import { listIncidentEvents } from './_tracking-core.mjs';

function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
export default async request=>{
  if(!validAdminSession(request))return Response.redirect(new URL('/admin-login.html',request.url),302);
  if(request.method!=='GET')return new Response('Method not allowed',{status:405});
  const events=await listIncidentEvents(300);const rows=events.map(e=>`<tr><td><strong>${esc(e.bookingId)}</strong><small>${esc(e.partnerId)}</small></td><td><span class="pill">${esc(e.status)}</span><small>${esc(e.createdAt)}</small></td><td>${esc(e.note||'—')}</td><td>${esc(e.condition||'—')}</td><td>${esc(e.claimStatus||'Belum dicatat')}<small>${esc(e.claimReference||'')}</small></td><td>${e.podId?`<a href="/.netlify/functions/pod-media?id=${encodeURIComponent(e.podId)}" target="_blank">Foto ↗</a>`:'—'}</td></tr>`).join('');
  return new Response(`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Klaim & Insiden | Libra</title><style>*{box-sizing:border-box}body{margin:0;background:#f2f6fa;color:#10243d;font-family:Inter,system-ui}.top{background:#061d36;color:#fff;padding:18px}.topin{max-width:1200px;margin:auto;display:flex;justify-content:space-between}.top a{color:#fff}.wrap{max-width:1200px;margin:auto;padding:24px 18px}.card{background:#fff;border:1px solid #dce5ee;border-radius:17px;overflow:hidden}.tablewrap{overflow:auto}table{width:100%;min-width:900px;border-collapse:collapse;font-size:13px}th,td{padding:11px;border-bottom:1px solid #edf1f5;text-align:left;vertical-align:top}th{background:#f7fafc}small{display:block;color:#718397;margin-top:4px}.pill{display:inline-block;padding:5px 8px;border-radius:999px;background:#ffe8e5;color:#a8332c;font-weight:800;font-size:11px}.empty{padding:28px}</style></head><body><header class="top"><div class="topin"><strong>LIBRA JAYA LOGISTIC • Klaim & Insiden</strong><a href="/admin-tool">← Home Admin</a></div></header><main class="wrap"><h1>Klaim & Insiden</h1><p>Daftar kejadian HELD, DAMAGED, dan CLAIM_PROCESS untuk ditindaklanjuti ke logistik pengirim.</p><section class="card">${rows?`<div class="tablewrap"><table><thead><tr><th>Booking</th><th>Status</th><th>Keterangan</th><th>Kondisi</th><th>Klaim Partner</th><th>Bukti</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<div class="empty">Belum ada insiden tercatat.</div>'}</section></main></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-frame-options':'DENY','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"}});
};
export const config={path:'/admin-claims'};
