import { adminDeniedResponse, listAdminAudit, requireAdminPermission } from './_admin-security.mjs';

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
export default async request=>{
 const auth=requireAdminPermission(request,'AUDIT_READ');if(!auth.ok)return adminDeniedResponse(request,auth);if(request.method!=='GET')return new Response('Method not allowed',{status:405});
 const rows=await listAdminAudit(700);const html=rows.map(r=>`<tr><td>${esc(r.createdAt)}</td><td><strong>${esc(r.username)}</strong><small>${esc(r.role)} • ${esc(r.ip||'')}</small></td><td>${esc(r.action)}</td><td>${esc(r.target||'—')}</td><td>${esc(r.result)}</td><td><code>${esc(JSON.stringify(r.details||{}))}</code></td></tr>`).join('');
 return new Response(`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Audit Admin | Libra</title><style>*{box-sizing:border-box}body{margin:0;background:#f2f6fa;color:#10243d;font-family:Inter,system-ui}.top{background:#061d36;color:#fff;padding:18px}.topin{max-width:1250px;margin:auto;display:flex;justify-content:space-between}.top a{color:#fff}.wrap{max-width:1250px;margin:auto;padding:24px 18px}.card{background:#fff;border:1px solid #dce5ee;border-radius:17px;overflow:hidden}.tablewrap{overflow:auto;max-height:720px}table{width:100%;min-width:1000px;border-collapse:collapse;font-size:13px}th,td{padding:10px 12px;border-bottom:1px solid #edf1f5;text-align:left;vertical-align:top}th{background:#f7fafc;position:sticky;top:0}small{display:block;color:#718397;margin-top:4px}code{font-size:11px;white-space:pre-wrap;word-break:break-word}.empty{padding:28px}</style></head><body><header class="top"><div class="topin"><strong>LIBRA JAYA LOGISTIC • Audit Admin</strong><a href="/admin-tool">← Home Admin</a></div></header><main class="wrap"><h1>Audit Trail</h1><p>Catatan perubahan operasional penting. Audit log tidak digunakan untuk menyimpan PIN, API secret, private key, atau token.</p><section class="card">${html?`<div class="tablewrap"><table><thead><tr><th>Waktu</th><th>Admin</th><th>Aksi</th><th>Target</th><th>Hasil</th><th>Detail</th></tr></thead><tbody>${html}</tbody></table></div>`:'<div class="empty">Belum ada audit event.</div>'}</section></main></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-frame-options':'DENY','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"}});
};
export const config={path:'/admin-audit'};
