import type { Config } from '@netlify/functions';
import { probeAccurateCustomerByName, resolveLatestActiveCustomer } from './_accurate-sales-order-core.mjs';
import { accurateGet } from './_accurate-core.mjs';
import { postHcSalesInvoice } from './_hc-accurate-si-production-core.mts';

const clean=(v:unknown,n=500)=>String(v??'').trim().slice(0,n);
const money=(v:unknown)=>Math.max(0,Math.round(Number(v)||0));
const norm=(v:unknown)=>clean(v,240).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const rowsOf=(d:any)=>Array.isArray(d?.d)?d.d:Array.isArray(d?.d?.data)?d.d.data:[];
function authorized(req:Request){const expected=clean(Netlify.env.get('LIBRA_HC_BRIDGE_SECRET'),500);const got=clean(req.headers.get('x-libra-hc-secret'),500);return Boolean(expected&&got&&expected===got);}

type CustomerMap={customerNo:string;accurateName:string;aliases:string[]};
function customerMaster():CustomerMap[]{return [
 {customerNo:'C.00024',accurateName:'Ibu Herly',aliases:['Ibu Herly','Ibu herly/Pak Yudi','Herli','Herly','Herli Camp','Herly Camp']},
 {customerNo:'C.00201',accurateName:'KIL - HC SPR',aliases:['KIL','KIL - HC SPR']}
];}
function mappedCustomer(name:string){const n=norm(name);if(!n)return null;return customerMaster().find(m=>m.aliases.some(a=>n===norm(a)))||null;}
async function verifyMappedCustomer(m:CustomerMap,sourceName:string){const probe=await probeAccurateCustomerByName(m.customerNo);const exact=(probe?.matches||[]).find((x:any)=>norm(x?.no)===norm(m.customerNo));if(!exact)throw new Error(`Mapping customer HC ${sourceName} menunjuk ${m.customerNo}, tetapi Customer No tersebut tidak ditemukan di Accurate.`);return {selected:exact,recommended:exact,matches:probe.matches,count:probe.count,queriedName:m.customerNo,sourceName,mapping:'HC_CUSTOMER_MASTER_EXACT',verifiedCustomerNo:true};}
function customerRow(x:any){return {id:x?.id??null,no:clean(x?.no,120),name:clean(x?.name,240),suspended:x?.suspended,disabled:x?.disabled,active:x?.active,lastUpdate:x?.lastUpdate??null,updatedAt:x?.updatedAt??null,createDate:x?.createDate??null,createdAt:x?.createdAt??null};}
function usableCustomer(x:any){return x?.active!==false&&x?.disabled!==true&&x?.suspended!==true&&Boolean(clean(x?.no,120)&&clean(x?.name,240));}
function scoreCustomer(x:any,q:string){const n=norm(x?.name),no=norm(x?.no);if(n===q||no===q)return 1000;if(n.startsWith(q))return 800-Math.min(200,n.length-q.length);if(n.includes(q))return 600-Math.min(200,n.length-q.length);const tokens=q.split(' ').filter(Boolean),hit=tokens.filter(t=>n.includes(t)).length;if(hit)return 300+hit*50;return 0;}
async function fuzzyCustomers(name:string){const q=norm(name);if(!q)return [];const rows:any[]=[];let page=1,pageCount=1,fields='id,no,name,suspended,disabled,active,lastUpdate,updatedAt,createDate,createdAt';do{let data:any;try{({data}=await accurateGet('customer','list',{'sp.pageSize':100,'sp.page':page,fields}));}catch{fields='id,no,name';({data}=await accurateGet('customer','list',{'sp.pageSize':100,'sp.page':page,fields}));}rows.push(...rowsOf(data));pageCount=Math.max(1,Math.min(Number(data?.sp?.pageCount)||1,100));page++;}while(page<=pageCount);return rows.map(customerRow).filter(usableCustomer).map(x=>({x,score:scoreCustomer(x,q)})).filter(v=>v.score>0).sort((a,b)=>b.score-a.score||String(a.x.name).localeCompare(String(b.x.name))).slice(0,20).map(v=>v.x);}
async function resolveCustomer(name:string){
 const mapped=mappedCustomer(name);
 if(mapped){try{return await verifyMappedCustomer(mapped,name);}catch(e:any){return {selected:null,recommended:null,matches:[],count:0,sourceName:name,mapping:'HC_CUSTOMER_MASTER_EXACT',mappedCustomerNo:mapped.customerNo,error:clean(e?.message||e,500),verifiedCustomerNo:false};}}
 try{const probe=await probeAccurateCustomerByName(name);if(probe?.matches?.length){let selected:any=null;try{selected=resolveLatestActiveCustomer(probe);}catch{}return {selected,recommended:selected,matches:probe.matches,count:probe.count,queriedName:name,sourceName:name,mapping:'ACTIVE_NAME_MATCH',verifiedActive:Boolean(selected)};}const matches=await fuzzyCustomers(name);return {selected:matches.length===1?matches[0]:null,recommended:matches.length===1?matches[0]:null,matches,count:matches.length,queriedName:name,sourceName:name,mapping:matches.length?'FUZZY_NAME_CANDIDATES':'UNMAPPED',verifiedActive:matches.length===1};}
 catch(e:any){return {selected:null,recommended:null,matches:[],count:0,sourceName:name,mapping:'UNMAPPED',error:clean(e?.message||e,500),verifiedActive:false};}
}
function salesInvoicePreview(body:any){const customerName=clean(body?.customerName,160),customerNo=clean(body?.customerNo,120),goods=Array.isArray(body?.goods)?body.goods:[];if(!customerName||!customerNo)throw new Error('Customer HC/Accurate wajib.');if(!goods.length)throw new Error('Rincian barang kosong.');const detailItem:any[]=[];let cargo=0,totalKg=0,totalKoli=0;for(const r of goods){const name=clean(r?.name||r?.description,160),kg=Number(r?.kg??r?.weight)||0,koli=Number(r?.koli)||0,rate=money(r?.rate??r?.tariff);if(!name||kg<=0||rate<=0)throw new Error('Nama barang, kg, dan tarif wajib > 0.');const total=money(kg*rate);cargo+=total;totalKg+=kg;totalKoli+=koli;detailItem.push({itemNo:'100001',quantity:kg,unitPrice:rate,detailName:`Jasa Kargo Udara HC - ${customerName} - ${name}`,detailNotes:`${koli} koli`,departmentName:'Kargo HC Sentani'});}const insurance=money(body?.insuranceAdmin),handling=money(body?.handling);if(insurance>0)detailItem.push({itemNo:'100020',quantity:1,unitPrice:insurance,detailName:`Asuransi+Admin WMA - ${customerName}`,departmentName:'Kargo HC Sentani'});if(handling>0)detailItem.push({itemNo:'100014',quantity:1,unitPrice:handling,detailName:`Handling Fee - ${customerName}`,departmentName:'Kargo HC Sentani'});const computed=money(cargo+insurance+handling),declared=money(body?.total);if(computed!==declared)throw new Error(`Total detail Rp${computed.toLocaleString('id-ID')} tidak sama dengan Total Tagihan Rp${declared.toLocaleString('id-ID')}.`);return {guard:'PREVIEW_ONLY_NO_POST',customer:{no:customerNo,name:customerName},header:{branchName:'HC Kargo Sentani',projectName:'HC SPR',salesmanName:'Wahyudi Utomo',currencyCode:'IDR'},summary:{lineCount:detailItem.length,totalKoli,totalKg,cargo,insuranceAdmin:insurance,handling,total:computed},detailItem};}
export default async(req:Request)=>{if(req.method!=='POST')return Response.json({ok:false,error:'Method Not Allowed'},{status:405});if(!authorized(req))return Response.json({ok:false,error:'Unauthorized bridge'},{status:404});try{const body:any=await req.json(),action=clean(body?.action,40).toLowerCase();if(action==='probe_customer'){const result=await resolveCustomer(clean(body?.customerName,240));return Response.json({ok:true,action,result},{headers:{'cache-control':'no-store'}});}if(action==='prepare_sales_invoice'){const result=salesInvoicePreview(body);return Response.json({ok:true,action,result},{headers:{'cache-control':'no-store'}});}if(action==='post_sales_invoice'){if(clean(body?.confirmation,80)!=='POST_HC_SALES_INVOICE')return Response.json({ok:false,error:'Konfirmasi POST Faktur HC tidak valid.'},{status:400,headers:{'cache-control':'no-store'}});const sourceId=clean(body?.sourceId,120);if(!sourceId)throw new Error('sourceId/tagihan ID wajib untuk idempotensi.');const preview=salesInvoicePreview(body);const result=await postHcSalesInvoice(preview,sourceId,{transDate:body?.transDate,description:body?.description});return Response.json({ok:true,action,result},{headers:{'cache-control':'no-store'}});}return Response.json({ok:false,error:'Aksi bridge belum diizinkan.'},{status:400,headers:{'cache-control':'no-store'}});}catch(e:any){const msg=clean(e?.message||e,1000),reconcile=msg.startsWith('RECONCILE_REQUIRED:');return Response.json({ok:false,reconcileRequired:reconcile,error:msg},{status:reconcile?409:500,headers:{'cache-control':'no-store'}});}};
export const config:Config={path:['/api/hc-accurate-bridge','/.netlify/functions/hc-accurate-bridge']};
