import type { Config } from '@netlify/functions';
import { probeAccurateCustomerByName } from './_accurate-sales-order-core.mjs';
import { postHcSalesInvoice } from './_hc-accurate-si-production-core.mts';

const clean=(v:unknown,n=500)=>String(v??'').trim().slice(0,n);
const money=(v:unknown)=>Math.max(0,Math.round(Number(v)||0));
const norm=(v:unknown)=>clean(v,240).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
function authorized(req:Request){const expected=clean(Netlify.env.get('LIBRA_HC_BRIDGE_SECRET'),500);const got=clean(req.headers.get('x-libra-hc-secret'),500);return Boolean(expected&&got&&expected===got);}
function customerRow(x:any){return {id:x?.id??null,no:clean(x?.no,120),name:clean(x?.name,240),suspended:x?.suspended,disabled:x?.disabled,active:x?.active};}
function usableCustomer(x:any){return x?.active!==false&&x?.disabled!==true&&x?.suspended!==true&&Boolean(clean(x?.no,120)&&clean(x?.name,240));}
async function resolveCustomer(customerNo:string,sourceName:string){const no=clean(customerNo,120),source=clean(sourceName,240);if(!no)return {selected:null,recommended:null,matches:[],count:0,sourceName:source,customerNo:no,mapping:'MASTER_ACCURATE_ID',registered:false,error:'ID Accurate dari Master Konsinyi kosong.'};try{const probe=await probeAccurateCustomerByName(no);const matches=(Array.isArray(probe?.matches)?probe.matches:[]).map(customerRow).filter(usableCustomer);const exact=matches.find((x:any)=>norm(x.no)===norm(no))||null;if(!exact)return {selected:null,recommended:null,matches,count:matches.length,sourceName:source,customerNo:no,queriedName:no,mapping:'MASTER_ACCURATE_ID',registered:false,error:`ID Customer Accurate ${no} tidak dapat diverifikasi.`};return {selected:exact,recommended:exact,matches:[exact],count:1,sourceName:source,customerNo:no,queriedName:no,mapping:'MASTER_ACCURATE_ID',registered:true,verifiedCustomerNo:true};}catch(e:any){return {selected:null,recommended:null,matches:[],count:0,sourceName:source,customerNo:no,queriedName:no,mapping:'MASTER_ACCURATE_ID',registered:false,error:clean(e?.message||e,500)};}}
function invoicePreview(body:any){const customerName=clean(body?.customerName,240),customerNo=clean(body?.customerNo,120),goods=Array.isArray(body?.goods)?body.goods:[];if(!customerNo)throw new Error('ID Customer Accurate wajib.');if(!goods.length)throw new Error('Rincian barang kosong.');const detailItem:any[]=[];let cargo=0,totalKg=0,totalKoli=0;for(const r of goods){const name=clean(r?.name||r?.description,160),kg=Number(r?.kg??r?.weight)||0,koli=Number(r?.koli)||0,rate=money(r?.rate??r?.tariff);if(!name||kg<=0||rate<=0)throw new Error('Nama barang, kg, dan tarif wajib > 0.');const total=money(kg*rate);cargo+=total;totalKg+=kg;totalKoli+=koli;detailItem.push({itemNo:'100001',quantity:kg,unitPrice:rate,detailName:`Jasa Kargo Udara HC${customerName?' - '+customerName:''} - ${name}`,detailNotes:`${koli} koli`,departmentName:'Kargo HC Sentani',projectName:'HC SPR'});}const insurance=money(body?.insuranceAdmin),handling=money(body?.handling);if(insurance>0)detailItem.push({itemNo:'100020',quantity:1,unitPrice:insurance,detailName:`Asuransi+Admin WMA${customerName?' - '+customerName:''}`,departmentName:'Kargo HC Sentani',projectName:'HC SPR'});if(handling>0)detailItem.push({itemNo:'100014',quantity:1,unitPrice:handling,detailName:`Handling Fee${customerName?' - '+customerName:''}`,departmentName:'Kargo HC Sentani',projectName:'HC SPR'});const computed=money(cargo+insurance+handling),declared=money(body?.total);if(computed!==declared)throw new Error(`Total detail Rp${computed.toLocaleString('id-ID')} tidak sama dengan Total Tagihan Rp${declared.toLocaleString('id-ID')}.`);return {guard:'PREVIEW_ONLY_NO_POST',documentType:'SALES_INVOICE',customer:{no:customerNo,name:customerName},header:{branchName:'HC Kargo Sentani',projectName:'HC SPR',currencyCode:'IDR'},summary:{lineCount:detailItem.length,totalKoli,totalKg,cargo,insuranceAdmin:insurance,handling,total:computed},detailItem};}
export default async(req:Request)=>{if(req.method!=='POST')return Response.json({ok:false,error:'Method Not Allowed'},{status:405});if(!authorized(req))return Response.json({ok:false,error:'Unauthorized bridge'},{status:404});try{const body:any=await req.json(),action=clean(body?.action,40).toLowerCase();if(action==='probe_customer'){const result=await resolveCustomer(clean(body?.customerNo,120),clean(body?.customerName,240));return Response.json({ok:true,action,result},{headers:{'cache-control':'no-store'}});}if(action==='prepare_sales_invoice'){const result=invoicePreview(body);return Response.json({ok:true,action,result},{headers:{'cache-control':'no-store'}});}if(action==='post_sales_invoice'){if(clean(body?.confirmation,80)!=='POST_HC_SALES_INVOICE')return Response.json({ok:false,error:'Konfirmasi POST Faktur Penjualan HC tidak valid.'},{status:400,headers:{'cache-control':'no-store'}});const sourceId=clean(body?.sourceId,120);if(!sourceId)throw new Error('sourceId/tagihan ID wajib untuk idempotensi.');const preview=invoicePreview(body);const result=await postHcSalesInvoice(preview,sourceId,{transDate:clean(body?.transDate,80),description:clean(body?.description||`Libra Tools HC ${sourceId}`,500)});return Response.json({ok:true,action,result},{headers:{'cache-control':'no-store'}});}return Response.json({ok:false,error:'Aksi bridge belum diizinkan.'},{status:400,headers:{'cache-control':'no-store'}});}catch(e:any){const msg=clean(e?.message||e,1000);return Response.json({ok:false,error:msg},{status:500,headers:{'cache-control':'no-store'}});}};
export const config:Config={path:['/api/hc-accurate-bridge','/.netlify/functions/hc-accurate-bridge']};
