(()=>{
  const byId=id=>document.getElementById(id);const clean=v=>String(v??'').trim();const nativeFetch=window.fetch.bind(window);let seq=0;
  function status(text,type=''){const el=byId('smuStatus');if(!el)return;el.textContent=text;el.className=`status ${text?'show':''} ${type}`;}
  function rowTemplate(){const id=++seq;return `<tr data-smu-row="${id}"><td><input class="smu-number" data-f="smuNumber" maxlength="80" placeholder="SMU/AWB" autocomplete="off"></td><td><input data-f="airline" maxlength="80" placeholder="Trigana/Garuda"></td><td><input data-f="flightNumber" maxlength="40" placeholder="IL-..." autocomplete="off"></td><td><input data-f="flightDate" type="date"></td><td><input class="smu-route" data-f="origin" maxlength="20" placeholder="CGK"></td><td><input class="smu-route" data-f="destination" maxlength="20" placeholder="DJJ"></td><td><input data-f="pieces" type="number" min="1" step="1" placeholder="1"></td><td><input data-f="weightKg" type="number" min="0.01" step="0.01" placeholder="0"></td><td><input class="smu-commodity" data-f="commodity" maxlength="160" placeholder="General cargo"></td><td><button type="button" class="smu-remove" data-remove-smu="${id}">×</button></td></tr>`;}
  function rows(){return [...document.querySelectorAll('[data-smu-row]')];}
  function addRow(){byId('smuRows').insertAdjacentHTML('beforeend',rowTemplate());bindRows();refreshSummary();}
  function bindRows(){document.querySelectorAll('[data-smu-row] input').forEach(el=>{if(el.dataset.smuBound)return;el.dataset.smuBound='1';el.addEventListener('input',refreshSummary);el.addEventListener('change',refreshSummary);});document.querySelectorAll('[data-remove-smu]').forEach(btn=>{if(btn.dataset.smuBound)return;btn.dataset.smuBound='1';btn.addEventListener('click',()=>{if(rows().length<=1)return;btn.closest('[data-smu-row]')?.remove();refreshSummary();});});}
  function readItem(row){const value=f=>clean(row.querySelector(`[data-f="${f}"]`)?.value);return {smuNumber:value('smuNumber').toUpperCase(),airline:value('airline').toUpperCase(),flightNumber:value('flightNumber').toUpperCase(),flightDate:value('flightDate'),origin:value('origin').toUpperCase(),destination:value('destination').toUpperCase(),pieces:Number(value('pieces')),weightKg:Number(value('weightKg')),commodity:value('commodity')};}
  function current(){const items=rows().map(readItem);const totalPieces=items.reduce((n,x)=>n+(Number.isFinite(x.pieces)?x.pieces:0),0);const totalWeightKg=Number(items.reduce((n,x)=>n+(Number.isFinite(x.weightKg)?x.weightKg:0),0).toFixed(2));return {smuMode:byId('smuMode')?.value||'SINGLE',smus:items,summary:{smuCount:items.length,totalPieces,totalWeightKg}};}
  function validate(){const data=current();if(!data.smus.length)throw new Error('Minimal 1 SMU wajib diinput.');if(data.smuMode==='SINGLE'&&data.smus.length!==1)throw new Error('Mode 1 SMU hanya boleh berisi satu SMU.');if(data.smuMode==='GABUNGAN'&&data.smus.length<2)throw new Error('Mode Gabungan minimal 2 SMU.');const seen=new Set();data.smus.forEach((x,i)=>{const label=x.smuNumber||`#${i+1}`;if(!x.smuNumber)throw new Error(`SMU #${i+1}: nomor SMU wajib.`);if(seen.has(x.smuNumber))throw new Error(`Nomor SMU duplikat: ${x.smuNumber}.`);seen.add(x.smuNumber);if(!x.airline)throw new Error(`SMU ${label}: maskapai wajib.`);if(!x.origin||!x.destination)throw new Error(`SMU ${label}: origin dan destination wajib.`);if(!Number.isInteger(x.pieces)||x.pieces<1)throw new Error(`SMU ${label}: jumlah koli minimal 1.`);if(!Number.isFinite(x.weightKg)||x.weightKg<=0)throw new Error(`SMU ${label}: berat wajib lebih dari 0 kg.`);});return data;}
  function refreshSummary(){const data=current();if(byId('weight'))byId('weight').value=data.summary.totalWeightKg||'';if(byId('smuCountSummary'))byId('smuCountSummary').textContent=`${data.summary.smuCount} SMU`;if(byId('smuPiecesSummary'))byId('smuPiecesSummary').textContent=`${data.summary.totalPieces} koli`;if(byId('smuWeightSummary'))byId('smuWeightSummary').textContent=`${data.summary.totalWeightKg.toLocaleString('id-ID',{maximumFractionDigits:2})} kg`;status('');window.libraSmuManifest=data;}
  function setMode(){const mode=byId('smuMode').value;byId('addSmuBtn').hidden=mode!=='GABUNGAN';if(mode==='SINGLE'){while(rows().length>1)rows().at(-1).remove();}else if(rows().length<2)addRow();refreshSummary();}
  function syntheticError(message){return new Response(JSON.stringify({message}),{status:400,headers:{'content-type':'application/json'}});}
  window.fetch=async(input,init)=>{
    const url=typeof input==='string'?input:(input?.url||'');const isQuote=url.includes('/.netlify/functions/partner-quote')&&!url.includes('partner-quote-status');const isBooking=url.includes('/.netlify/functions/partner-booking-create');
    if((isQuote||isBooking)&&String(init?.method||'GET').toUpperCase()==='POST'){
      let manifest;try{manifest=validate();status(`SMU valid • ${manifest.summary.smuCount} SMU • ${manifest.summary.totalPieces} koli • ${manifest.summary.totalWeightKg} kg`,'ok');}catch(error){status(error.message,'err');return syntheticError(error.message);}
      try{const body=typeof init.body==='string'?JSON.parse(init.body):{};if(isQuote)body.weightKg=manifest.summary.totalWeightKg;if(isBooking){body.smuMode=manifest.smuMode;body.smus=manifest.smus;body.cargoType=body.cargoType||'SMU_AIR_CARGO';}init={...init,body:JSON.stringify(body)};}catch(error){return syntheticError('Payload SMU booking tidak dapat diproses.');}
    }
    return nativeFetch(input,init);
  };
  byId('addSmuBtn')?.addEventListener('click',()=>{if(rows().length>=30){status('Maksimum 30 SMU dalam satu booking gabungan.','err');return;}addRow();});byId('smuMode')?.addEventListener('change',setMode);addRow();setMode();
})();
