const $=id=>document.getElementById(id);let routes=[],currentRoute=null,currentQuote=null;
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)||0);
function status(el,text,type=''){el.textContent=text;el.className=`status show ${type}`;}
function requireLogin(res){if(res.status===401){location.href='/partner/login.html?next=/partner/booking.html';return true;}return false;}
async function loadRoutes(){try{const res=await fetch('/.netlify/functions/partner-routes');if(requireLogin(res))return;const data=await res.json();if(!res.ok)throw new Error(data.message||'Master rute gagal dimuat.');routes=data.routes||[];$('route').innerHTML='<option value="">Pilih kelurahan / kampung tujuan</option>'+routes.map((r,i)=>`<option value="${i}">${r.kelurahan} — ${r.distrik}, ${r.kabupatenKota} • ${r.kodeRute}</option>`).join('');}catch(e){$('route').innerHTML='<option value="">Master rute tidak tersedia</option>';status($('quoteStatus'),e.message,'err');}}
$('route').addEventListener('change',()=>{currentRoute=routes[Number($('route').value)]||null;currentQuote=null;$('bookingBtn').disabled=true;$('refreshQuote').hidden=true;});
$('quoteBtn').addEventListener('click',async()=>{currentRoute=routes[Number($('route').value)]||null;const weight=Number($('weight').value);if(!currentRoute||!weight){status($('quoteStatus'),'Pilih tujuan dan isi berat kiriman.','err');return;}status($('quoteStatus'),'Meminta quote…');try{const res=await fetch('/.netlify/functions/partner-quote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kodeRute:currentRoute.kodeRute,weightKg:weight})});if(requireLogin(res))return;const data=await res.json();if(!res.ok)throw new Error(data.message||'Quote gagal.');currentQuote=data.quote;$('refreshQuote').hidden=false;renderQuote();}catch(e){status($('quoteStatus'),e.message,'err');}});
function renderQuote(){if(!currentQuote)return;const approved=currentQuote.status==='APPROVED';const detail=`${currentQuote.quoteId} • ${currentQuote.kelurahan}, ${currentQuote.distrik} • ${currentQuote.weightKg} kg${currentQuote.sla?' • SLA '+currentQuote.sla:''}`;status($('quoteStatus'),approved?`APPROVED — ${money(currentQuote.amount)} — ${detail}`:`${currentQuote.status} — ${detail}. Menunggu approval Admin Libra sebelum booking.`,approved?'ok':'');$('bookingBtn').disabled=!approved;}
$('refreshQuote').addEventListener('click',async()=>{if(!currentQuote)return;try{const res=await fetch('/.netlify/functions/partner-quote-status?quoteId='+encodeURIComponent(currentQuote.quoteId));if(requireLogin(res))return;const data=await res.json();if(!res.ok)throw new Error(data.message||'Gagal membaca quote.');currentQuote=data.quote;renderQuote();}catch(e){status($('quoteStatus'),e.message,'err');}});
$('gpsBtn').addEventListener('click',()=>{if(!currentRoute){status($('gpsStatus'),'Pilih rute/kelurahan terlebih dahulu.','err');return;}if(!navigator.geolocation){status($('gpsStatus'),'Perangkat tidak mendukung GPS browser.','err');return;}status($('gpsStatus'),'Mengambil GPS…');navigator.geolocation.getCurrentPosition(pos=>{const c=pos.coords;$('lat').value=c.latitude.toFixed(7);$('lng').value=c.longitude.toFixed(7);$('accuracy').value=Math.round(c.accuracy)+' m';$('confirmedArea').value=`${currentRoute.kelurahan}, ${currentRoute.distrik}`;if(c.accuracy>200)status($('gpsStatus'),`Akurasi ${Math.round(c.accuracy)} m. Harus 200 m atau lebih baik. Coba di area terbuka.`,'err');else status($('gpsStatus'),`GPS terkunci. Akurasi ${Math.round(c.accuracy)} m.`,'ok');},err=>status($('gpsStatus'),'GPS gagal: '+err.message,'err'),{enableHighAccuracy:true,timeout:15000,maximumAge:0});});
$('bookingBtn').addEventListener('click',async()=>{if(!currentQuote||currentQuote.status!=='APPROVED'){status($('bookingStatus'),'Quote belum APPROVED.','err');return;}const lat=Number($('lat').value),lng=Number($('lng').value),accuracy=Number(String($('accuracy').value).replace(/[^0-9.]/g,''));if(!$('confirmKel').checked||!Number.isFinite(lat)||!Number.isFinite(lng)||!accuracy||accuracy>200){status($('bookingStatus'),'GPS tujuan dan konfirmasi kelurahan wajib valid.','err');return;}const payload={quoteId:currentQuote.quoteId,idempotencyKey:crypto.randomUUID(),partnerReference:$('partnerRef').value,sender:{name:$('senderName').value,phone:$('senderPhone').value,address:$('senderAddress').value},recipient:{name:$('recipientName').value,phone:$('recipientPhone').value,address:$('recipientAddress').value},destination:{kodeWilayah:currentRoute.kodeWilayah,latitude:lat,longitude:lng,accuracyMeters:accuracy,confirmedKelurahan:true}};status($('bookingStatus'),'Membuat booking…');$('bookingBtn').disabled=true;try{const res=await fetch('/.netlify/functions/partner-booking-create',{method:'POST',headers:{'content-type':'application/json','idempotency-key':payload.idempotencyKey},body:JSON.stringify(payload)});if(requireLogin(res))return;const data=await res.json();if(res.status===402){status($('bookingStatus'),`${data.message} Booking ID: ${data.bookingId||'—'}. Saldo: ${money(data.balance)}. Silakan top-up di menu Saldo.`,'err');return;}if(!res.ok)throw new Error(data.message||'Booking gagal.');status($('bookingStatus'),`Booking berhasil: ${data.booking.bookingId}. Saldo tersisa ${money(data.balance)}.`,'ok');currentQuote.status='BOOKED';}catch(e){status($('bookingStatus'),e.message,'err');}finally{if(currentQuote?.status==='APPROVED')$('bookingBtn').disabled=false;}});
loadRoutes();